local STRINGS = GLOBAL.STRINGS

local coffeeTypes = {
	"espresso",
	"latte",
	"cappuccino",
	"iced_coffee",
	"black_coffee",
	"frappe",
	"caramel_macchiato",
	"coffee_milkshake",
}

STRINGS.NAMES.DUG_COFFEEBUSH = "挖出的咖啡灌木"
STRINGS.NAMES.COFFEEBUSH = "咖啡灌木"
STRINGS.NAMES.COFFEEBEANS = "咖啡豆"
STRINGS.NAMES.COFFEEBEANS_COOKED = "烤咖啡豆"
STRINGS.NAMES.COFFEE = "咖啡"
STRINGS.NAMES.COFFEE_GROUND = "细磨咖啡"
STRINGS.NAMES.CAFFEINE = "咖啡因"
STRINGS.NAMES.LATTE = "拿铁"
STRINGS.NAMES.CAPPUCCINO = "卡布奇诺"
STRINGS.NAMES.ESPRESSO = "浓缩咖啡"
STRINGS.NAMES.ICED_COFFEE = "冰咖啡"
STRINGS.NAMES.BLACK_COFFEE = "纯黑咖啡"
STRINGS.NAMES.FRAPPE = "冰沙咖啡"
STRINGS.NAMES.CARAMEL_MACCHIATO = "焦糖玛奇朵"
STRINGS.NAMES.SHAKER_WOOD = "木制摇匀器"
STRINGS.NAMES.SHAKER_GOLD = "豪华摇匀器"
STRINGS.NAMES.COFFEE_FILTER = "咖啡过滤器"
STRINGS.NAMES.COFFEE_MILKSHAKE = "咖啡奶昔"

for _, coffeeType in pairs(coffeeTypes) do
	local key = string.upper(coffeeType)
	STRINGS.CHARACTERS.GENERIC.DESCRIBE[key] = "终于...一杯新鲜的咖啡，最好的品种！"
  STRINGS.CHARACTERS.WILLOW.DESCRIBE[key] = "黑得像木炭。烧得很好。香气：烟熏。烫手。"
  STRINGS.CHARACTERS.WOLFGANG.DESCRIBE[key] = "咖啡让沃尔夫冈想去踢屁股，为了正义！"
  STRINGS.CHARACTERS.WENDY.DESCRIBE[key] = "我喜欢这个色调。像丧葬服装一样。"
  STRINGS.CHARACTERS.WX78.DESCRIBE[key] = "这个燃料出奇地高效。"
  STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE[key] = "它黑暗得就像尼福尔海姆的深渊... 会让女武神继续战斗！"
  STRINGS.CHARACTERS.WEBBER.DESCRIBE[key] = "妈妈会告诉爸爸不要太晚喝咖啡。"
  STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE[key] = "失眠从未困扰过我。"
  STRINGS.CHARACTERS.WOODIE.DESCRIBE[key] = "它有木香味。我最喜欢这种方式的咖啡。要是我也有涂了黄油的烤饼就好了..."
  STRINGS.CHARACTERS.WAXWELL.DESCRIBE[key] = "终于到了！就像在Cisco的时候。虽然不是里茨酒店，但现在能用了。"
end


STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBUSH = "等等... 咖啡灌木？在这里？你知道你在错误的生物群系吗？"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.COFFEEBUSH = "我们能跳过这尴尬的阶段，直接烧你的豆子吗？"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COFFEEBUSH = "呸，那些浆果！生吃太苦了！"
STRINGS.CHARACTERS.WENDY.DESCRIBE.COFFEEBUSH = "有人可以用这些浆果冲咖啡了，黑得像最黑暗的地牢。"
STRINGS.CHARACTERS.WX78.DESCRIBE.COFFEEBUSH = "实验性燃料植物。"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.COFFEEBUSH = "弗雷尔已经祝福了你，咖啡灌木。"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.COFFEEBUSH = "闻起来像爸爸的咖啡！"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.COFFEEBUSH = "这个家伙闻起来有点像咖啡。"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COFFEEBUSH = "这个咖啡属的植物显然适应了当地的气候条件。"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COFFEEBUSH = "这是我在这里能找到的最接近咖啡馆的地方了。"


STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_COFFEEBUSH = "我自己的种植园的起点。"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DUG_COFFEEBUSH = "要烧咖啡豆，我需要先种植它。"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DUG_COFFEEBUSH = "我种植，你给咖啡。"
STRINGS.CHARACTERS.WENDY.DESCRIBE.DUG_COFFEEBUSH = "我们应该培养它吗，Abigail？"
STRINGS.CHARACTERS.WX78.DESCRIBE.DUG_COFFEEBUSH = "基于咖啡的燃料蓝图。"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DUG_COFFEEBUSH = "我应该种植它来取悦弗雷尔。"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.DUG_COFFEEBUSH = "让我们来园艺吧！"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.DUG_COFFEEBUSH = "我们可以通过这个家伙种植自己的咖啡。"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DUG_COFFEEBUSH = "让我们看看气候是否适合。"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DUG_COFFEEBUSH = "为了一杯咖啡，我得采取这些措施..."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS = "现在，真正的问题是：如何将它们变成咖啡？"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.COFFEEBEANS = "见识一下我的幸运打火机，准备被烧焦吧！"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COFFEEBEANS = "呸。沃尔夫冈还需要更多工作。"
STRINGS.CHARACTERS.WENDY.DESCRIBE.COFFEEBEANS = "我将献祭它们来满足我对黑暗液体的渴望。"
STRINGS.CHARACTERS.WX78.DESCRIBE.COFFEEBEANS = "肉体生物把一切都复杂化了。"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COFFEEBEANS = "形态完整的不开裂核果。"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.COFFEEBEANS = "还不到喝咖啡和烤饼干的时候，Luce..."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.COFFEEBEANS = "我应该查探一下弗雷尔希望我如何处理这些豆子。"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.COFFEEBEANS = "我觉得爸爸不是这样吃那些豆子的。"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COFFEEBEANS = "哈！咖啡师，我需要你在这个时候出现！"


STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS_COOKED = "现在它们应该可以食用了。但是...我的咖啡..."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.COFFEEBEANS_COOKED = "你烧得很好。我很欣赏你，小豆子。"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COFFEEBEANS_COOKED = "还是有点苦，但不错。"
STRINGS.CHARACTERS.WENDY.DESCRIBE.COFFEEBEANS_COOKED = "你已经死了。这是正式的。"
STRINGS.CHARACTERS.WX78.DESCRIBE.COFFEEBEANS_COOKED = "次级燃料变种。"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.COFFEEBEANS_COOKED = "看起来足够可食用，嗯？"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.COFFEEBEANS_COOKED = "它们的牺牲将不会被遗忘。"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COFFEEBEANS_COOKED = "我可不是非洲灵猫，不能以这种状态食用它。"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.COFFEEBEANS_COOKED = "有点像妈妈为爸爸煮咖啡的味道。"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COFFEEBEANS_COOKED = "我开始因为其中的手艺而讨厌咖啡了。"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEE_GROUND = "闻起来很不错。"