local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.CARROT_CAKE = "胡萝卜蛋糕"
STRINGS.NAMES.PUMPKIN_SLICES = "烤南瓜"
STRINGS.NAMES.STUFFED_GOURD = "酿南瓜"
STRINGS.NAMES.STEAMED_GRANATE = "蒸石榴"
STRINGS.NAMES.GLOMEGGS = "恶魔蛋"
STRINGS.NAMES.BUTTERCAKE = "牛油蛋糕"
STRINGS.NAMES.POMEJUICE = "石榴汁"
STRINGS.NAMES.CORNDOG = "玉米狗"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CARROT_CAKE = "一个用于处理剩余兔子食物的地方！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PUMPKIN_SLICES = "这是一个小南瓜。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.STUFFED_GOURD = "用于漫长的万圣节晚上的欢庆。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.STEAMED_GRANATE = "终于能用得上这些了。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.POMEJUICE = "炎热的日子里的冷饮。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORNDOG = "玉米棒！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUTTERCAKE = "蛋和蜂蜜，一切都晴朗！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLOMEGGS = "这个健康吗？"