local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.LARGECHEST = "大型箱子"
STRINGS.RECIPE_DESC.LARGECHEST = "一个用于存放更多物品的大型箱子。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LARGECHEST = "起来很高级！"

STRINGS.NAMES.LARGEICEBOX = "大型冰箱"
STRINGS.RECIPE_DESC.LARGEICEBOX = "一个巨大的冰箱。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LARGEICEBOX = "我掌握了冰冷的力量！"