local STRINGS = GLOBAL.STRINGS

-- NAMES
STRINGS.NAMES.ACK_MUFFIN = "方便玛芬"
  -- Breads (x4)
STRINGS.NAMES.SHAMCAKES = "莓果煎饼"
STRINGS.NAMES.NANA_BREAD = "香蕉面包"
STRINGS.NAMES.HARDTACK = "硬饼干"
STRINGS.NAMES.FRUIT_MUFFIN = "水果玛芬"

  -- Cakes & Pies (x5)
STRINGS.NAMES.SPICED_CAKE = "节日蛋糕" -- Honeyed, HOT
STRINGS.NAMES.CACTUS_CAKE = "仙人掌蛋糕" -- Requires Cactus
STRINGS.NAMES.MERINGUE = "蛋白酥皮派"
STRINGS.NAMES.TARTE_TATIN = "美味蛋挞"
STRINGS.NAMES.STICKY_BUN = "黏糕" -- Honeyed
  -- Candies & Sugars (x5+)
STRINGS.NAMES.CANDY_SPONGE = "海绵糖" -- Honeyed
STRINGS.NAMES.MUSH_MELON = "蜜瓜糖" -- Honeyed
STRINGS.NAMES.MUSH_MELON_COOKED = "烤蜜瓜糖" -- Honeyed
STRINGS.NAMES.CANDIED_NUT = "糖煮坚果" -- Honeyed
STRINGS.NAMES.CANDIED_FRUIT = "糖渍水果" -- Honeyed
STRINGS.NAMES.CANDIED_BACON = "焦糖培根" -- Honeyed
  -- Eggs (x5)
STRINGS.NAMES.OMELETTE = "蓬松煎蛋"
STRINGS.NAMES.NOPALITO = "仙人掌炒蛋" -- Requires Cactus
STRINGS.NAMES.SALAD_EGG = "蛋沙拉"
STRINGS.NAMES.EGG_FOO_YUNG = "芙蓉炒蛋"
STRINGS.NAMES.MUSHY_EGGS = "烂煮鸡蛋"
  -- Fruits (x4)
STRINGS.NAMES.LIMONADE = "柠檬汽水" -- COLD - Requires Ice
STRINGS.NAMES.LIMONGELO = "果冻"
STRINGS.NAMES.FRUIT_LEATHER = "水果皮革"
STRINGS.NAMES.FRUIT_TRUFFLE = "水果松露" -- Requires Dairy (not fat/butter/oleo)

	-- Ice Recipes (x4)
STRINGS.NAMES.SOUP_BROTH = "肉汤" -- Requires Ice
STRINGS.NAMES.JUICE_WATERBERRY = "果味冰沙" -- COLD - Requires Ice
STRINGS.NAMES.SOUP_WATERCRESS = "西洋菜汤" -- Requires Ice
STRINGS.NAMES.TEA_FLORAL = "花草茶" -- Requires Ice

  -- Ingredients	(x5)
STRINGS.NAMES.OLEO = "牛油" -- Ingredient: Dairy, Fat
STRINGS.NAMES.FLOUR_GROUND = "面粉粉末" -- Ingredient: Flour, Requires Flora
STRINGS.NAMES.FRUIT_SYRUP = "粘糖浆" -- Honeyed, Ingredient: Sweetener, Fruit
STRINGS.NAMES.MOLASSES = "糖蜜" -- Honeyed, Ingredient: Sweetener, Requires Mole
STRINGS.NAMES.COCONUT_MILK = "椰奶" -- Ingredient: Dairy, Requires Ice
  -- Liquors (x5+)
STRINGS.NAMES.LIQUOR = "烈酒" -- Cold - requires Ice
STRINGS.NAMES.MARGARITA = "玛格丽特" -- Cold - requires Ice
STRINGS.NAMES.PINA_COLADA = "琴奈可拉达" -- Cold - requires Ice
STRINGS.NAMES.DAIQUIRI = "戴基利" -- Cold - requires Ice
STRINGS.NAMES.VINO = "葡萄酒" -- Cold - requires Ice
STRINGS.NAMES.PINOT_NOIR = "陈年红酒"
  -- Meats (Beef) (x5)
STRINGS.NAMES.BEEF_BUTTER = "黄油牛柳"
STRINGS.NAMES.KIYMALI_PIDE = "肉饼面包"
STRINGS.NAMES.COLDCUTS = "冷切肉" -- COLD - Requires Ice
STRINGS.NAMES.BRACIOLE = "牛肉卷"
STRINGS.NAMES.BEEF_STIRFRY = "牛肉炒面"
  -- Meats (Pork) (x5+)
STRINGS.NAMES.SAUSAGE_GRAVY = "香肠和肉汁"
STRINGS.NAMES.DUMPLING_PORK = "蒸饺"
STRINGS.NAMES.SPICED_SAUSAGE = "香辣香肠" -- HOT
STRINGS.NAMES.SAUSAGE_COOKED = "烤香肠" -- HOT
STRINGS.NAMES.SAUSAGE_DRIED = "腌制莎莉美"
STRINGS.NAMES.SPICED_HAM = "热带火腿" -- HOT
STRINGS.NAMES.SWEET_N_SOUR = "糖醋大餐"
	-- Meats (Poultry)  (x5)
STRINGS.NAMES.LO_MEIN_CHICKEN = "鸡肉捞面"
STRINGS.NAMES.BEEFALO_WINGS = "牛羊翅膀" -- HOT
STRINGS.NAMES.ROLLATINI = "鸡肉卷"
STRINGS.NAMES.PICATTA = "柑橘鸡肉"
STRINGS.NAMES.SALAD_WALDORF = "瓦尔多夫沙拉"
	-- Meats (Seafood)  (x5)
STRINGS.NAMES.SURF_N_TURF = "陆地与海洋大餐" -- Latin translation "Surf Turffe" use 'Land and Sea Plate' for foreign translations
STRINGS.NAMES.TENTACICLE = "触手"
STRINGS.NAMES.STUFFED_TOMANGO = "海鲜填充蔬菜"
STRINGS.NAMES.FISH_N_CHIPS = "炸鱼薯条"
STRINGS.NAMES.SLURRY_SEAFOOD = "海鲜糊"
	-- Meats (Shellfish)  (x5)
STRINGS.NAMES.LOBSTER_FAKED = "烤龙虾"
STRINGS.NAMES.SHELLFISH_BUTTER = "煎炒贝类"
STRINGS.NAMES.CAKE_CRAB = "蟹肉蛋糕" -- Requires crabbit, A meat based cake
STRINGS.NAMES.TEMPURA_SHRIMP = "脆皮虾"
STRINGS.NAMES.SCALLOPS_SPICY = "四川干贝"
	-- Monster	(x2)
STRINGS.NAMES.BEEF_MAXWELL = "魔鬼牛肉" -- Requires Monster
STRINGS.NAMES.DURIAN_DELIGHT = "幸运蛋糕" -- 'daifuku' Requires Monster/Fruit
STRINGS.NAMES.HAKARL = "腌鱼" -- 'Hakarl' Requires Monster/Fish
STRINGS.NAMES.MONSTER_BURGER = "野兽汉堡" -- Requires Monster

  -- Mushrooms (x4)
STRINGS.NAMES.MUSHROOM_MEDLEY = "蘑菇大杂烩"
STRINGS.NAMES.MUSHROOM_BURGER = "蘑菇汉堡"
STRINGS.NAMES.CITRUS_MUSHROOM = "烤柑橘蘑菇"
STRINGS.NAMES.MUSHROOM_STEW = "蘑菇炖汤"

  -- Nuts and Seeds (x4+)
STRINGS.NAMES.NUT_BUTTER = "坚果酱" -- Requires Nut
STRINGS.NAMES.KUNG_PAO = "辣宫保鸡丁"
STRINGS.NAMES.CHEESE_LOG = "坚果奶酪卷" -- Requires Dairy (not butter/oleo)
STRINGS.NAMES.PORRIDGE = "粥"
STRINGS.NAMES.GRUEL = "剩菜粥"

  -- Salads (x4)
STRINGS.NAMES.SALAD_CARROT = "柑橘沙拉"
STRINGS.NAMES.SALAD_GRAPE = "葡萄沙拉"
STRINGS.NAMES.SALAD_YAMION = "烤蔬菜沙拉"
STRINGS.NAMES.SALAD_BLOOM = "野花沙拉"

  -- Sandwiches(x5)
STRINGS.NAMES.SANDWICH_BLT = "经典三明治"
STRINGS.NAMES.SANDWICH_BLT_HALF = "半个三明治"
STRINGS.NAMES.SANDWICH_VEGGIE = "蔬菜三明治"
STRINGS.NAMES.SANDWICH_VEGGIE_HALF = "半个三明治"
STRINGS.NAMES.SANDWICH_CROQUE = "女士烤三明治"
STRINGS.NAMES.SANDWICH_CROQUE_HALF = "半个烤三明治"
STRINGS.NAMES.SANDWICH_BANANA = "炸香蕉三明治"
STRINGS.NAMES.SANDWICH_BANANA_HALF = "半个香蕉三明治"
STRINGS.NAMES.SANDWICH_JAM = "果酱三明治"
STRINGS.NAMES.SANDWICH_JAM_HALF = "半个果酱三明治"
  -- Snacks (x5)
STRINGS.NAMES.TAKOYAKI = "章鱼烧"
STRINGS.NAMES.YAMION_RINGS = "炸洋葱圈"
STRINGS.NAMES.POPCORN_BUTTERY = "黄油爆米花"
STRINGS.NAMES.TWICE_BAKED = "烤蔬菜块"
STRINGS.NAMES.ALOO_TIKI = "烤土豆饼"
  -- Soups (x5)
STRINGS.NAMES.SOUP_SQUASH = "南瓜浓汤" -- Requires Nut
STRINGS.NAMES.CACTUS_SOUP = "仙人掌汤" -- Requires Cactus
STRINGS.NAMES.SOUP_CHOWDER = "海鲜杂烩汤"
STRINGS.NAMES.GUMBO = "杂菜炖饭" -- HOT
STRINGS.NAMES.COLD_GAZPACHO = "冷番茄汤" -- COLD - requires Ice
  -- Spiced Foods (x5)
STRINGS.NAMES.DRAGON_ROLL = "龙卷寿司" -- Sushi Roll w/ Dragon Fruit -- HOT (Low heat for very long period)
STRINGS.NAMES.SPICED_RUM = "香料朗姆酒" -- HOT (As Daiquri but hot instead of cold)
STRINGS.NAMES.PIKO_SALSA = "辣味莎莎酱" -- HOT
STRINGS.NAMES.SPICED_FISH = "韩式鱼汤" -- HOT (Korean Fish Stew)
STRINGS.NAMES.SALAD_SPICED = "泰式沙拉" -- HOT
	-- Bonus & Hidden Recipes	(x4)
STRINGS.NAMES.CASSEROLE = "法国砂锅" -- Ingredient: Meat, Veggie, Precook
STRINGS.NAMES.MOONCAKE_SIMPLE = "月饼" -- Catchall for flour
STRINGS.NAMES.MUSHROOM_MALODY = "蘑菇狂想曲"
STRINGS.NAMES.LEFTOVERS = "剩菜"

	-- Crops & Seeds
STRINGS.NAMES.GRAPRICOT = "葡桃"
STRINGS.NAMES.GRAPRICOT_COOKED = "炖葡桃"
STRINGS.NAMES.GRAPRICOT_DRIED = "干果"
STRINGS.NAMES.GRAPRICOT_SEEDS = "葡桃种子"
STRINGS.NAMES.TOMANGO = "番茄芒果"
STRINGS.NAMES.TOMANGO_COOKED = "煎番茄芒果"
STRINGS.NAMES.TOMANGO_DRIED = "晒干的番茄芒果"
STRINGS.NAMES.TOMANGO_SEEDS = "番茄芒果种子"
STRINGS.NAMES.LIMON = "酸柠"
STRINGS.NAMES.LIMON_COOKED = "烤酸柠"
STRINGS.NAMES.LIMON_SEEDS = "酸柠种子"
STRINGS.NAMES.YAMION = "洋葱薯"
STRINGS.NAMES.YAMION_COOKED = "烤洋葱薯"
STRINGS.NAMES.YAMION_SEEDS = "洋葱薯种子"
STRINGS.NAMES.GARLEEK = "蒜蒜"
STRINGS.NAMES.GARLEEK_COOKED = "烤蒜蒜"
STRINGS.NAMES.ROCKY_MEAT = "岩石龙虾尾"
STRINGS.NAMES.ROCKY_MEAT_COOKED = "烤龙虾尾"
STRINGS.NAMES.TENTACLE_MEAT = "生触手"
STRINGS.NAMES.TENTACLE_MEAT_COOKED = "炒鱿鱼"
STRINGS.NAMES.RUTABEETA = "红萝菜"
STRINGS.NAMES.RUTABEETA_COOKED = "煮红萝菜"
STRINGS.NAMES.RUTABEETA_PLANT = "野生红萝菜"
STRINGS.NAMES.RUTABEETA_SEEDS = "红萝菜种子"
STRINGS.NAMES.GUAVACADO_COOKED = "切片的鳄梨"
STRINGS.NAMES.GUAVACADO = "鳄梨"
STRINGS.NAMES.GUAVACADO_SEEDS = "鳄梨种子"
	-- Shipwrecked Crops
STRINGS.NAMES.PAPAYANAPPLE = "木瓜苹果"
STRINGS.NAMES.PAPAYANAPPLE_COOKED = "烤木瓜苹果"
STRINGS.NAMES.ZUCCHILLI = "西葫椒"
STRINGS.NAMES.ZUCCHILLI_COOKED = "切片的西葫椒"
STRINGS.NAMES.ZUCCHILLI_SEEDS = "西葫椒种子"

-- =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+    DESCRIPTIONS.GENERIC (WILSON)   =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+

STRINGS.CHARACTERS.GENERIC.DESCRIBE.ACK_MUFFIN  = { "一个松饼玛格芬。", } -- A Macguffin is an object or device used soley to advance the plot in a story
	-- Breads (x4)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHAMCAKES  = { "这些非常好吃。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NANA_BREAD  = { "比水果蛋糕好吃多了。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HARDTACK  = { "不太开胃，但保存得很好。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRUIT_MUFFIN  = { "它比水果蛋糕更好吃。", }

  -- Cakes & Pies (x5)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICED_CAKE  = { "一块香气扑鼻的节日蛋糕。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CACTUS_CAKE  = { "甜而多刺。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MERINGUE  = { "轻盈、松软和甜美的糖果。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TARTE_TATIN  = { "一块格纹挞饼。", } -- Tartan : A pattern of criss-crossed horizontal and vertical bands 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.STICKY_BUN  = { "超级黏糊的面包卷。", }
  -- Candies & Sugars (x5)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CANDY_SPONGE  = { "多孔的甜点。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSH_MELON  = { "不完全是我记忆中的样子。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSH_MELON_COOKED  = { "我想再吃一些。", } -- S'mores : A campfire desert made using marshmallows
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CANDIED_NUT  = { "表面涂有结晶蜜糖的坚果。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CANDIED_FRUIT  = { "涂上蜜糖的甜腻水果。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CANDIED_BACON  = { "黄油糖浸泡的咸甜培根。", }
  -- Eggs (x5)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OMELETTE  = { "打破几个鸡蛋的结果。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NOPALITO  = { "美味但多刺的一对。", } -- Nopalito : A dish made with nopales, the flat stems of prickly pear cactus
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SALAD_EGG  = { "任何野餐的主食。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EGG_FOO_YUNG  = { "煎蛋和蔬菜的肉饼。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHY_EGGS  = { "可食用的鸡蛋。", }
  -- Fruits (x4)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMONADE  = { "一杯冷饮，酸甜可口。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMONGELO  = { "总是有空间来品尝果冻。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRUIT_LEATHER  = { "水果干片。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRUIT_TRUFFLE  = { "一种琐碎的甜点。", } -- Trifling : Reference to Fruit Trifle 

  -- Ice Recipes (x4)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JUICE_WATERBERRY = { "冰多于水果。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SOUP_BROTH = { "有点太稀了。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SOUP_WATERCRESS = { "湿漉漉的煮熟蔬菜。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_FLORAL = { "正好可以让我头脑清醒。", }

-- Ingredients (x5)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OLEO  = { "还不错，但我更喜欢黄油的味道。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLOUR_GROUND = { "多用途的面粉。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRUIT_SYRUP  = { "高果糖糖浆。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOLASSES  = { "熬制而成的甜糖浆。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT_MILK  = { "椰子汁？太坚果了。", }
-- Liquors (x5+)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIQUOR  = { "加了一点小桶和杜松子酒。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MARGARITA  = { "但是我丢了盐罐。", } -- Musical Reference : "Margaritaville" by Jimmy Buffett
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PINA_COLADA  = { "是的，我喜欢椰子松酒。", } -- Musical Reference : "Escape (Pina Colada song)" by Rupert Holmes 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DAIQUIRI  = { "这款戴基利里太果香了。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VINO  = { "稍微让人镇静一点的东西。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PINOT_NOIR  = { "另一种稍微让人镇静一点的东西。", }
-- Meats (Beef) (x5)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEEF_BUTTER = { "用炒香的青葱煮的嫩牛肉。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KIYMALI_PIDE  = { "薄片面饼上的绞肉。", } -- Turkish 'pizza' 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COLDCUTS  = { "完美的冷肉片。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BRACIOLE  = { "烤过的填充牛肉片。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEEF_STIRFRY = { "我在炒菜时想到的这个主意。", } -- pun, Wok is a shallow pan used for cooking stir-fry dishes
  -- Meats (Pork) (x5)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAUSAGE_GRAVY  = { "油腻的香肠和肥肉汁。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUMPLING_PORK  = { "带有调味肉馅的面团袋子。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICED_SAUSAGE  = { "这不是最差的香肠。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAUSAGE_COOKED  = { "串烤的香肠。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAUSAGE_DRIED  = { "夏日食用的香肠。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICED_HAM  = { "一种热带假日的美食。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_N_SOUR  = { "它让我再次感受到湖南的味道。", }
  -- Meats (Poultry) (x5)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LO_MEIN_CHICKEN  = { "这些面条相当引人注目。", }  -- Cantonese origin 'lou min' stirred noodles
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEEFALO_WINGS  = { "超级辣。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROLLATINI  = { "薄切、卷起和烤制的菜肴。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PICATTA  = { "一道柑橘类家禽菜肴。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SALAD_WALDORF  = { "向厨师致以我的敬意。", }
  -- Meats (Seafood) (x5)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SURF_N_TURF  = { "美味的双重风味组合。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TENTACICLE  = { "串烤章鱼触手。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.STUFFED_TOMANGO  = { "海鲜填料。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_N_CHIPS  = { "美味的双重风味组合。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLURRY_SEAFOOD  = { "这里有些可疑的味道。", }
  -- Meats (Shellfish) (x5)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOBSTER_FAKED  = { "不如一顿丰盛的晚餐，但还算可以接受。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHELLFISH_BUTTER  = { "放在半壳上，配以香草和浓郁的黄油酱。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAKE_CRAB = { "看起来像蛋糕...尝起来像螃蟹。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEMPURA_SHRIMP = { "轻微的炸鲜美。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCALLOPS_SPICY = {"调味酱才是重点。", } -- Rick and Morty reference
  -- Monster (x4)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEEF_MAXWELL = { "肮脏的肉在蓬松的酥皮中。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DURIAN_DELIGHT = { "一种怪异的甜蛋糕。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAKARL = { "一种令人发指的臭味。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONSTER_BURGER = { "一顿巨大的餐点。", }

	-- Mushrooms (x4)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHROOM_MEDLEY  = { "一种迷人的多彩真菌组合。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHROOM_BURGER  = { "热肉夹在蘑菇盖之间。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CITRUS_MUSHROOM  = { "需要大蒜。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHROOM_STEW  = { "一碗奶油蘑菇汤。", }

	-- Nuts and Seeds (x4)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NUT_BUTTER  = { "饮食科学的巅峰。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KUNG_PAO  = { "坚果和肉类的辣椒混合物。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHEESE_LOG  = { "比木头更可食用。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORRIDGE  = { "一种完美的味觉调和。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRUEL  = { "一种不完美的味觉调和。", }

	-- Salads (x4)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SALAD_CARROT  = { "比烤胡萝卜更好吃。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SALAD_GRAPE  = { "还不太对，但勉强可以。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SALAD_YAMION  = { "它有浓郁的味道。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SALAD_BLOOM  = { "它主要是装饰而已。", }

  -- Sandwiches (x4)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDWICH_BLT  = { "一份肉、生菜和蔬菜三明治。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDWICH_BLT_HALF  = { "一份肉、生菜和蔬菜三明治的小吃。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDWICH_VEGGIE  = { "沙拉夹在面包里。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDWICH_VEGGIE_HALF  = { "蔬菜小吃三明治。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDWICH_CROQUE  = { "就像早餐一样，只是更脆。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDWICH_CROQUE_HALF  = { "就像脆脆的早午餐。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDWICH_BANANA  = { "一份甜美多汁的水果三明治。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDWICH_BANANA_HALF  = { "一份甜美多汁的小吃。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDWICH_JAM  = { "它让我想起童年的回忆。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDWICH_JAM_HALF  = { "我记得小时候吃过这个。", }
--STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDWICH_SAUSAGE  = { "Hot sausage in a bun.", }
	-- Snacks (x6 +)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAKOYAKI = { "小巧滑溜的小吃。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ALOO_TIKI  = { "有点脆脆的。", } -- Hinidi- Tikki: A small croquette (food item name derived from french word for crunch)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.YAMION_RINGS  = { "一种熟悉而令人安慰的小吃。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TWICE_BAKED  = { "装满肉，滴着黄油。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.POPCORN_BUTTERY = { "加了黄油和盐，尝起来像咸黄油。" } -- Terry Pratchett, Moving Pictures

  -- Soups (x5)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SOUP_SQUASH  = { "搅碎得完美无缺。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CACTUS_SOUP  = { "一桶美味。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SOUP_CHOWDER  = { "浓稠而滑腻。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GUMBO  = { "格外辛辣的美味佳肴。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COLD_GAZPACHO  = { "最好冷藏后享用。", }
  -- Spiced Foods (x5)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGON_ROLL  = { "一份美味的天妇罗，加点辣味。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICED_RUM  = { "一点点让我感到温暖的东西。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIKO_SALSA = { "伽利略最喜欢的菜肴。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICED_FISH = { "一碗滚烫的炖鱼。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SALAD_SPICED  = { "凉爽与辣味的完美结合。", }
	-- Bonus and Hidden Recipes	(x4)
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LEFTOVERS = { "不如原味好吃。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONCAKE_SIMPLE = { "一块咸香的糕点。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHROOM_MALODY  = { "它闻起来像腐烂。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CASSEROLE = { "又是剩菜。", }

-- Crops & Seeds
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRAPRICOT = { "葡萄树结出的果实。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRAPRICOT_COOKED = { "美味又甜蜜。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRAPRICOT_DRIED = { "干燥了，但仍然很甜。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRAPRICOT_SEEDS = { "这些种子是果核。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMON = { "酸味的柑橘类水果。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMON_COOKED = { "现在看起来不太吸引人了。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIMON_SEEDS = { "这些种子可以长出柑橘树。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOMANGO = { "有人争论这是水果还是蔬菜。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOMANGO_DRIED = { "美味的蔬菜片...或水果片。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOMANGO_COOKED = { "有些人喜欢在它们还是绿色的时候烹饪。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOMANGO_SEEDS = { "这是水果的种子还是蔬菜的种子？", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.YAMION = { "一种可食用的块茎。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.YAMION_COOKED = { "它可以一层一层地剥开。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.YAMION_SEEDS = { "我甚至不知道它们有种子。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GARLEEK = { "一种具有刺激性气味的葱头。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GARLEEK_COOKED = { "气味很浓郁。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCKY_MEAT = { "让我想起了石蟹的故事。", } -- Pun 'story' = 'tale' 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCKY_MEAT_COOKED= { "石烤龙虾尾。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TENTACLE_MEAT = { "换取对等的鱿鱼。", } -- Quid pro Quo : Latin phrase meaning an even exchange 'this for that'
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TENTACLE_MEAT_COOKED = { "美味的触手。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RUTABEETA = { "根茎类蔬菜。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RUTABEETA_COOKED = { "没什么能超越它。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RUTABEETA_PLANT = { "我希望能找到其中之一。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RUTABEETA_SEEDS = { "根的根。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GUAVACADO_COOKED = { "可怜的水果。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GUAVACADO = { "一个又大又长的梨。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GUAVACADO_SEEDS = { "超级种子。", }
  -- Shipwrecked Crops
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PAPAYANAPPLE  = { "一个奇怪的水果。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PAPAYANAPPLE_COOKED  = { "新鲜烤制的水果。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ZUCCHILLI  = { "一种辛辣的小型南瓜。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ZUCCHILLI_COOKED  = { "一盘辣辣的片状食物。", }
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ZUCCHILLI_SEEDS  = { "小小的包装中有很多香料。", }

-- =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+    DESCRIPTIONS.WX78     =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+

  -- Breads (x4)
STRINGS.CHARACTERS.WX78.DESCRIBE.SHAMCAKES  = { "错误：太美味了！", }
STRINGS.CHARACTERS.WX78.DESCRIBE.NANA_BREAD  = { "食物里面的食物", }
STRINGS.CHARACTERS.WX78.DESCRIBE.HARDTACK  = { "粗糙的食物物质", }
STRINGS.CHARACTERS.WX78.DESCRIBE.FRUIT_MUFFIN  = { "小食物里的小食物", }

  -- Cakes & Pies (x5)
STRINGS.CHARACTERS.WX78.DESCRIBE.SPICED_CAKE  = { "加热后的甜点", }
STRINGS.CHARACTERS.WX78.DESCRIBE.CACTUS_CAKE  = { "让他们吃蛋糕", }
STRINGS.CHARACTERS.WX78.DESCRIBE.MERINGUE  = { "经过硬化的蛋类成分", }
STRINGS.CHARACTERS.WX78.DESCRIBE.STICKY_BUN  = { "额外的黏性检测到", }
STRINGS.CHARACTERS.WX78.DESCRIBE.TARTE_TATIN  = { "倒置的糕点", }
  -- Candies & Sugars (x5+)
STRINGS.CHARACTERS.WX78.DESCRIBE.CANDY_SPONGE  = { "请提交审查报价的想法。", }
STRINGS.CHARACTERS.WX78.DESCRIBE.CANDIED_BACON  = { "糖浸泡的肉", }
STRINGS.CHARACTERS.WX78.DESCRIBE.CANDIED_FRUIT  = { "饱和葡萄糖的水果", }
STRINGS.CHARACTERS.WX78.DESCRIBE.CANDIED_NUT  = { "甜美的植物之味", }
STRINGS.CHARACTERS.WX78.DESCRIBE.MUSH_MELON  = { "既不是蘑菇也不是瓜", }
STRINGS.CHARACTERS.WX78.DESCRIBE.MUSH_MELON_COOKED  = { "既不是蘑菇也不是瓜，也不是烤面包", }
  -- Eggs (x5)
STRINGS.CHARACTERS.WX78.DESCRIBE.OMELETTE  = { "我已经打败了鸡蛋", }
STRINGS.CHARACTERS.WX78.DESCRIBE.NOPALITO  = { "未改良的沙漠营养", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SALAD_EGG  = { "蛋的混合物", }
STRINGS.CHARACTERS.WX78.DESCRIBE.EGG_FOO_YUNG  = { "炒蛋夹饼", } --  Thai version Khai Chiao Yat Sai means "stuffed fried egg".
STRINGS.CHARACTERS.WX78.DESCRIBE.MUSHY_EGGS  = { "这个甚至更不好", }
  -- Fruits (x4)
STRINGS.CHARACTERS.WX78.DESCRIBE.LIMONADE  = { "冰镇的清洁溶液", }
STRINGS.CHARACTERS.WX78.DESCRIBE.LIMONGELO  = { "果冻状的水果永动机", }
STRINGS.CHARACTERS.WX78.DESCRIBE.FRUIT_LEATHER  = { "压缩干燥的水果", }
STRINGS.CHARACTERS.WX78.DESCRIBE.FRUIT_TRUFFLE  = { "悬浮在奶制品中的生果", }

  -- Ice Recipes (x4)
STRINGS.CHARACTERS.WX78.DESCRIBE.SOUP_BROTH = { "饱和的蛋白质", }
STRINGS.CHARACTERS.WX78.DESCRIBE.JUICE_WATERBERRY = { "半液体状态", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SOUP_WATERCRESS = { "饱和的植物物质", }
STRINGS.CHARACTERS.WX78.DESCRIBE.TEA_FLORAL = { "热沙拉水", } -- 'Teen Titans Go' reference

  -- Ingredients (x4)
STRINGS.CHARACTERS.WX78.DESCRIBE.OLEO  = { "仿制的不可能性", }
STRINGS.CHARACTERS.WX78.DESCRIBE.FLOUR_GROUND = { "粉状食物物质", }
STRINGS.CHARACTERS.WX78.DESCRIBE.FRUIT_SYRUP  = { "蜜饯果汁", }
STRINGS.CHARACTERS.WX78.DESCRIBE.MOLASSES  = { "甜蜜可疑的方法", }
STRINGS.CHARACTERS.WX78.DESCRIBE.COCONUT_MILK  = { "液化的坚果营养", }

STRINGS.CHARACTERS.WX78.DESCRIBE.CASSEROLE  = { "食物的二次加热", }
  -- Liquors (x5+)
STRINGS.CHARACTERS.WX78.DESCRIBE.LIQUOR  = { "乙醇", }
STRINGS.CHARACTERS.WX78.DESCRIBE.MARGARITA  = { "冰冻乙醇", }
STRINGS.CHARACTERS.WX78.DESCRIBE.PINA_COLADA  = { "加糖乙醇", }
STRINGS.CHARACTERS.WX78.DESCRIBE.DAIQUIRI  = { "坚果基酒", }
STRINGS.CHARACTERS.WX78.DESCRIBE.VINO  = { "水果乙醇", }
STRINGS.CHARACTERS.WX78.DESCRIBE.PINOT_NOIR  = { "陈年水果乙醇", }
  -- Meats (Beef) (x5)
STRINGS.CHARACTERS.WX78.DESCRIBE.BEEF_BUTTER = { "肉浸泡在融化的脂肪中", }
STRINGS.CHARACTERS.WX78.DESCRIBE.KIYMALI_PIDE  = { "扁平的食物", }
STRINGS.CHARACTERS.WX78.DESCRIBE.COLDCUTS  = { "冰上的肉类", }
STRINGS.CHARACTERS.WX78.DESCRIBE.BRACIOLE  = { "肉卷", }
STRINGS.CHARACTERS.WX78.DESCRIBE.BEEF_STIRFRY = { "它让我充满灼热的烦躁", } -- pun sear = fry, agitation = stir
  -- Meats (Pork) (x5 +2)
STRINGS.CHARACTERS.WX78.DESCRIBE.SAUSAGE_GRAVY  = { "多脂等于多味道", }
STRINGS.CHARACTERS.WX78.DESCRIBE.DUMPLING_PORK  = { " ", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SPICED_SAUSAGE  = { "肉肠", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SAUSAGE_COOKED  = { "粘糊状的肉肠", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SAUSAGE_DRIED  = { "干燥的肉肠", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SPICED_HAM  = { "调味水果和肉", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SWEET_N_SOUR  = { "粘稠的甜酸涂层", }
  -- Meats (Poultry) (x5)
STRINGS.CHARACTERS.WX78.DESCRIBE.LO_MEIN_CHICKEN  = { "禽类的主要功能", }
STRINGS.CHARACTERS.WX78.DESCRIBE.BEEFALO_WINGS  = { "牦牛有翅膀？", }
STRINGS.CHARACTERS.WX78.DESCRIBE.ROLLATINI  = { "鸟肉卷在植物片中", }
STRINGS.CHARACTERS.WX78.DESCRIBE.PICATTA  = { "鸟肉在水果酱中", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SALAD_WALDORF  = { "鸟的部分嵌套在植物混合物中", } -- Computing reference- Nest: Place an element in a hierarchical arrangement
  -- Meats (Seafood) (x5)
STRINGS.CHARACTERS.WX78.DESCRIBE.SURF_N_TURF  = { "两个生物群落的肉混合在一起", }
STRINGS.CHARACTERS.WX78.DESCRIBE.TENTACICLE  = { "粘稠的冻却突起", }
STRINGS.CHARACTERS.WX78.DESCRIBE.STUFFED_TOMANGO  = { "水生动物肉在烤植物中", }
STRINGS.CHARACTERS.WX78.DESCRIBE.FISH_N_CHIPS  = { "获得薯片", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SLURRY_SEAFOOD  = { "水生食品浆糊", }
  -- Meats (Shellfish) (x5)
STRINGS.CHARACTERS.WX78.DESCRIBE.LOBSTER_FAKED  = { "勉强更糟的命运", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SHELLFISH_BUTTER  = { "在自身的壳中炖煮", }
STRINGS.CHARACTERS.WX78.DESCRIBE.CAKE_CRAB = { "装甲糕点", }
STRINGS.CHARACTERS.WX78.DESCRIBE.TEMPURA_SHRIMP = { "富含坚果的润滑蛋白质", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SCALLOPS_SPICY = {"四个回路的形状", } -- Scalloping: shaping by scooping out; Four Circuits: provisional division of Szechuan area of China
  -- Monster (x4)
STRINGS.CHARACTERS.WX78.DESCRIBE.BEEF_MAXWELL = { "肉在卷中", }
STRINGS.CHARACTERS.WX78.DESCRIBE.DURIAN_DELIGHT = { "又甜又臭", }
STRINGS.CHARACTERS.WX78.DESCRIBE.HAKARL = { "我可以品尝到气味", }
STRINGS.CHARACTERS.WX78.DESCRIBE.MONSTER_BURGER  = { "怪物嵌套在蘑菇中", } -- Computing reference- Nest: Place an element in a hierarchical arrangement

  -- Mushrooms (x4)
STRINGS.CHARACTERS.WX78.DESCRIBE.MUSHROOM_MEDLEY  = { "优化的真菌", }
STRINGS.CHARACTERS.WX78.DESCRIBE.MUSHROOM_BURGER  = { "肉嵌套在蘑菇中", } -- Computing reference- Nest: Place an element in a hierarchical arrangement
STRINGS.CHARACTERS.WX78.DESCRIBE.CITRUS_MUSHROOM  = { "黏糊糊的酸味真菌", }
STRINGS.CHARACTERS.WX78.DESCRIBE.MUSHROOM_STEW  = { "以乳制品为基础的真菌汤", }

  -- Nuts and Seeds (x4 +1)
STRINGS.CHARACTERS.WX78.DESCRIBE.NUT_BUTTER  = { "润滑的坚果营养", }
STRINGS.CHARACTERS.WX78.DESCRIBE.KUNG_PAO  = { " ", }
STRINGS.CHARACTERS.WX78.DESCRIBE.CHEESE_LOG  = { "发酵的哺乳动物汁液", }
STRINGS.CHARACTERS.WX78.DESCRIBE.PORRIDGE  = { "糊状种子壳", }
STRINGS.CHARACTERS.WX78.DESCRIBE.GRUEL  = { "超级糊状种子壳", }

  -- Salads (x4)
STRINGS.CHARACTERS.WX78.DESCRIBE.SALAD_CARROT  = { "润滑剂涂覆的营养食品", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SALAD_GRAPE  = { "制作的植物球", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SALAD_YAMION  = { "准备好的强效植物根茎", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SALAD_BLOOM  = { "我应该吃些美丽的东西吗？", }
  
  -- Sandwiches(x5 +5)
STRINGS.CHARACTERS.WX78.DESCRIBE.SANDWICH_BLT  = { "堆叠的令人恶心", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SANDWICH_BLT_HALF  = { "只有一半令人恶心", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SANDWICH_VEGGIE  = { "可食用的叶子组合", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SANDWICH_VEGGIE_HALF  = { "剥落的三明治", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SANDWICH_CROQUE  = { "一个未改良的三明治", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SANDWICH_CROQUE_HALF  = { "通过去除一半而改良", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SANDWICH_BANANA  = { "润滑的三明治", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SANDWICH_BANANA_HALF  = { "一个甜蜜而果香的小吃。", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SANDWICH_JAM  = { "探测到果酱面包", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SANDWICH_JAM_HALF  = { "果酱即将到来", }
  -- Snacks (x7 +)
STRINGS.CHARACTERS.WX78.DESCRIBE.TAKOYAKI = { "粘稠鱼肉球", }
STRINGS.CHARACTERS.WX78.DESCRIBE.YAMION_RINGS  = { "油炸的高效果圈", }
STRINGS.CHARACTERS.WX78.DESCRIBE.POPCORN_BUTTERY = { "油腻的卡路里", }
STRINGS.CHARACTERS.WX78.DESCRIBE.TWICE_BAKED  = { "加倍的效力", }
STRINGS.CHARACTERS.WX78.DESCRIBE.ALOO_TIKI  = { "硬化的蔬菜", }
  -- Soups (x5)
STRINGS.CHARACTERS.WX78.DESCRIBE.SOUP_SQUASH  = { "液体南瓜", }
STRINGS.CHARACTERS.WX78.DESCRIBE.CACTUS_SOUP  = { "去除了养分屏障的仙人掌汤", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SOUP_CHOWDER  = { "它们在水中游得更好", }
STRINGS.CHARACTERS.WX78.DESCRIBE.GUMBO  = { "剩菜等于炖菜", }
STRINGS.CHARACTERS.WX78.DESCRIBE.COLD_GAZPACHO  = { "内热的汤", }
  -- Spiced Foods (x5)
STRINGS.CHARACTERS.WX78.DESCRIBE.DRAGON_ROLL  = { "大块的蛋白质来源", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SPICED_RUM  = { "外热的乙醇", }
STRINGS.CHARACTERS.WX78.DESCRIBE.PIKO_SALSA  = { "从肉类机器获得的香料", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SPICED_FISH = { "辣味鱼汁", }
STRINGS.CHARACTERS.WX78.DESCRIBE.SALAD_SPICED  = { "切成片的辣味纤维素", }
  -- Bonus & Hidden Recipes	(x3)
STRINGS.CHARACTERS.WX78.DESCRIBE.CASSEROLE = { "又是剩菜。", }
STRINGS.CHARACTERS.WX78.DESCRIBE.MOONCAKE_SIMPLE = { "粗糙的混合食品味道", }
STRINGS.CHARACTERS.WX78.DESCRIBE.MUSHROOM_MALODY  = { "有害的真菌", }
STRINGS.CHARACTERS.WX78.DESCRIBE.LEFTOVERS = { "一个脆皮的残余物", } -- Cruft, computer jargon for leftover/disfunctional elements 


  -- Crops & Seeds
STRINGS.CHARACTERS.WX78.DESCRIBE.GRAPRICOT  = { "多汁的植物球", }
STRINGS.CHARACTERS.WX78.DESCRIBE.GRAPRICOT_COOKED  = { "球体已泄气", }
STRINGS.CHARACTERS.WX78.DESCRIBE.GRAPRICOT_SEEDS  = { "这就像是植物球的源代码", }
STRINGS.CHARACTERS.WX78.DESCRIBE.GRAPRICOT_DRIED  = { "球体已脱水", }
STRINGS.CHARACTERS.WX78.DESCRIBE.LIMON  = { "二进制风味", }
STRINGS.CHARACTERS.WX78.DESCRIBE.LIMON_COOKED  = { "风味稍微减弱了", }
STRINGS.CHARACTERS.WX78.DESCRIBE.LIMON_SEEDS  = { "这就像是二进制植物的源代码", }
STRINGS.CHARACTERS.WX78.DESCRIBE.TOMANGO  = { "本地蔬菜等于水果", }
STRINGS.CHARACTERS.WX78.DESCRIBE.TOMANGO_COOKED  = { "水果现在变成蔬菜了吗？", }
STRINGS.CHARACTERS.WX78.DESCRIBE.TOMANGO_DRIED  = { "蔬菜现在变成水果了吗？", }
STRINGS.CHARACTERS.WX78.DESCRIBE.TOMANGO_SEEDS  = { "能生长出蔬菜的水果种子", }
STRINGS.CHARACTERS.WX78.DESCRIBE.YAMION  = { "一种强效的植物根", }
STRINGS.CHARACTERS.WX78.DESCRIBE.YAMION_COOKED  = { "效力倍增", }
STRINGS.CHARACTERS.WX78.DESCRIBE.YAMION_SEEDS  = { "这就像是强效植物的源代码", }
STRINGS.CHARACTERS.WX78.DESCRIBE.GARLEEK  = { "气味胜过风味", }
STRINGS.CHARACTERS.WX78.DESCRIBE.GARLEEK_COOKED  = { "风味等同于气味", }
STRINGS.CHARACTERS.WX78.DESCRIBE.ROCKY_MEAT = { "后壳", }
STRINGS.CHARACTERS.WX78.DESCRIBE.ROCKY_MEAT_COOKED= { "富含营养的矿物质", }
STRINGS.CHARACTERS.WX78.DESCRIBE.TENTACLE_MEAT  = { "粘性附肢", }
STRINGS.CHARACTERS.WX78.DESCRIBE.TENTACLE_MEAT_COOKED  = { "附肢开胃菜", }
STRINGS.CHARACTERS.WX78.DESCRIBE.RUTABEETA = { "(甜菜)的根", }
STRINGS.CHARACTERS.WX78.DESCRIBE.RUTABEETA_COOKED = { "我打败了这个根", }
STRINGS.CHARACTERS.WX78.DESCRIBE.RUTABEETA_PLANT = { "可食用的根", }
STRINGS.CHARACTERS.WX78.DESCRIBE.RUTABEETA_SEEDS = { "这就像是植物的根的源代码", }

  -- Shipwrecked Crops
STRINGS.CHARACTERS.WX78.DESCRIBE.PAPAYANAPPLE  = { "水果的糅合体", }
STRINGS.CHARACTERS.WX78.DESCRIBE.PAPAYANAPPLE_COOKED  = { "烤糅合体片段", }
STRINGS.CHARACTERS.WX78.DESCRIBE.ZUCCHILLI  = { "发现特洛伊辣椒", } -- Computing reference- Trojan: A program that misleads users of its true intent
STRINGS.CHARACTERS.WX78.DESCRIBE.ZUCCHILLI_COOKED  = { "切片的特洛伊辣椒", }
STRINGS.CHARACTERS.WX78.DESCRIBE.ZUCCHILLI_SEEDS  = { "这就像是热量的源代码", }

-- =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+    DESCRIPTIONS.WOODIE     =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+

  -- Breads (x4)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SHAMCAKES  = { "没有枫糖浆吗？", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.NANA_BREAD  = { "果香的面包！", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FRUIT_MUFFIN  = { "水果味的松饼！", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.HARDTACK  = { "尝起来像烧焦的木头。", }

  -- Cakes & Pies (x5)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPICED_CAKE  = { "闻起来像家里的味道。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CACTUS_CAKE  = { "最危险的食物就是婚礼蛋糕。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MERINGUE  = { "就像外婆做的一样。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.STICKY_BUN  = { "粘在你的肚子里，嗯？", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TARTE_TATIN  = { "一个奇怪的小派。", }
  -- Candies & Sugars (x5+)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CANDY_SPONGE  = { "洞洞糖！", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CANDIED_BACON  = { "甜味肉类。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CANDIED_FRUIT  = { "浸泡在糖浆中的水果。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CANDIED_NUT  = { "坚果糖。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MUSH_MELON  = { "柔软的绿色零食。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MUSH_MELON_COOKED  = { "在树林里露营的完美选择。", }
  -- Eggs (x5)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.OMELETTE  = { "蓬松的蛋饼，嗯？", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.NOPALITO  = { "来自边境的口味，嗯？", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SALAD_EGG  = { "制作三明治的好食材。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.EGG_FOO_YUNG  = { "让我想起了圣保罗三明治。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MUSHY_EGGS  = { "稠蛋比稀蛋更好。", }
  -- Fruits (x4)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.LIMONADE  = { "炎热天气的绝佳饮品。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.LIMONGELO  = { "几乎像果冻一样。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FRUIT_LEATHER  = { "口感柔韧，但味道不错。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FRUIT_TRUFFLE  = { "有点水果味，嗯？", }

  -- Ice Recipes (x4)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SOUP_BROTH = { "像麋鹿水一样的味道。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.JUICE_WATERBERRY = { "水果味冰块。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SOUP_WATERCRESS = { "湿润的兔子食物，嗯？", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TEA_FLORAL = { "温暖又爽口。", }

  -- Ingredients (x5)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.OLEO  = { "比黄油好！", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FLOUR_GROUND = { "花看起来不是这样的。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FRUIT_SYRUP  = { "比起枫糖浆还差点。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MOLASSES  = { "我更喜欢枫糖浆。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.COCONUT_MILK  = { "有木头味道。", }
  -- Liquors (x5+)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.LIQUOR  = { "一杯凉爽的啤酒。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MARGARITA  = { "这啤酒太冷了。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PINA_COLADA  = { "这啤酒太甜了。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.DAIQUIRI  = { "看起来有点坚果味。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.VINO  = { "我更喜欢苦味啤酒。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PINOT_NOIR  = { "我还是更喜欢苦味啤酒。", }
  -- Meats (Beef) (x5)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEEF_BUTTER = { "请提交审核报价。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.KIYMALI_PIDE  = { "请提交审核报价。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.COLDCUTS  = { "就像回家的午餐一样。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BRACIOLE  = { "像一小块肉卷。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEEF_STIRFRY = { "请提交审核报价。", } 
  -- Meats (Pork) (x5+)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SAUSAGE_GRAVY  = { "就像在伐木营地里一样。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.DUMPLING_PORK  = { "请提交审核报价。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPICED_SAUSAGE  = { "请提交审核报价。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SAUSAGE_COOKED  = { "请提交审核报价。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SAUSAGE_DRIED  = { "请提交审核报价。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPICED_HAM  = { "请提交审核报价。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SWEET_N_SOUR  = { "酸甜口味的美味肉类。", }

  -- Meats (Seafood) (x3)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.STUFFED_TOMANGO  = { "那可真是一股奇怪的气味。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SURF_N_TURF  = { "闻起来像驼鹿鳕鱼派！", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FISH_N_CHIPS  = { "几乎没有什么气味。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.LOBSTER_FAKED  = { "不过你也可以用鲑鱼烤。", }

	-- Meats (Poultry) (x3)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ROLLATINI  = { "里面肯定有一只鸟。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEEFALO_WINGS  = { "用辣酱调味的鸟翅膀，嗯？", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PICATTA  = { "味道像鸡肉。", }
	-- Mushrooms (4+)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CITRUS_MUSHROOM  = { "我觉得加了水果会更好。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MUSHROOM_BURGER  = { "一个热蘑菇三明治，嗯？", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MUSHROOM_MALODY  = { "我煮对了吗？", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MUSHROOM_MEDLEY  = { "所有的蘑菇！", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MUSHROOM_STEW  = { "炖蘑菇。", }
	-- Salads (4)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SALAD_CARROT  = { "十月沙拉。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SALAD_GRAPE  = { "一堆浆果。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SALAD_WALDORF  = { "我猜这会成为一顿饭，嗯？", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SALAD_YAMION  = { "烤植物茎。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SALAD_BLOOM  = { "也许露西会喜欢这个。", }
	-- Soups (x5)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.COLD_GAZPACHO  = { "一个奇怪的小汤。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CACTUS_SOUP  = { "刺人的高汤。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SOUP_CHOWDER  = { "现在尝起来都是鱼腥味。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GUMBO  = { "汤怎么会把食物煮得这么辣？", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SOUP_SQUASH  = { "还是不是馅饼。", }
	-- Snacks (x7 +)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ALOO_TIKI  = { "咬一口会发出嘎吱嘎吱的声音，嗯？", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CHEESE_LOG  = { "我更喜欢砍木头。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GRUEL  = { "和家乡的早餐不一样。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.NUT_BUTTER  = { "这是最好的黄油！", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PORRIDGE  = { "和家乡的早餐一样。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.YAMION_RINGS  = { "我们在伐木营地吃这个。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TWICE_BAKED  = { "再次完美烘烤！", }
	-- Cookables (x4)
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CASSEROLE  = { "我猜它还是不错的。", }

	-- Crops & Seeds
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GRAPRICOT  = { "我从未去过葡萄园。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GRAPRICOT_COOKED  = { "它们看起来湿湿的。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GRAPRICOT_SEEDS  = { "我应该种很多这些。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GRAPRICOT_DRIED  = { "……", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.LIMON  = { "这些通常不是长在树上的吗？", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.LIMON_COOKED  = { "酸酸的烟熏味。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.LIMON_SEEDS  = { "种子一点也不酸。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TOMANGO  = { "一个奇怪的小水果。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TOMANGO_COOKED  = { "炸蔬菜。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TOMANGO_SEEDS  = { "希望我能种出更多。", }	
STRINGS.CHARACTERS.WOODIE.DESCRIBE.YAMION  = { "一个环状的小植物茎。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.YAMION_COOKED  = { "完美地烤熟了。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.YAMION_SEEDS  = { "我要种更多。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GARLEEK  = { "这些味道真难闻。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GARLEEK_COOKED  = { "至少现在味道好了一点。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ROCKY_MEAT = { "...", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ROCKY_MEAT_COOKED= { "...", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TENTACLE_MEAT  = { "...", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TENTACLE_MEAT_COOKED  = { "...", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.RUTABEETA = { "...", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.RUTABEETA_COOKED = { "...", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.RUTABEETA_PLANT = { "...", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.RUTABEETA_SEEDS = { "...", }


	-- Shipwrecked Crops
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PAPAYANAPPLE  = { "它有一层厚厚的叶子包裹着。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PAPAYANAPPLE_COOKED  = { "切起来就像切木头一样！", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ZUCCHILLI  = { "它闻起来像火。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ZUCCHILLI_COOKED  = { "连气味都灼伤。", }	
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ZUCCHILLI_SEEDS  = { "我不确定我是否想种更多。", }

	
-- =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+    DESCRIPTIONS.WILLOW     =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+


	-- Breads (x4)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SHAMCAKES  = { "我更喜欢叫它们热饼。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.NANA_BREAD  = { "比以前更美味。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FRUIT_MUFFIN  = { "一块美味的烤松饼。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.HARDTACK  = { "它们尝起来像灰烬。", }

	-- Cakes & Pies (x5)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPICED_CAKE  = { "它让我的嘴发热。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CACTUS_CAKE  = { "它需要点燃的蜡烛。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MERINGUE  = { "白色部分会因火而改变。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.STICKY_BUN  = { "它上面有蜂蜜浇面。", }
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TARTE_TATIN  = { "一个内部填满火色水果的糕点。", }
	-- Candies & Sugars (x5+)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CANDY_SPONGE  = { "好极了，有洞的糖果。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CANDIED_BACON  = { "覆盖了焦糖和烤焦。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CANDIED_FRUIT  = { "现在可能太甜了。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CANDIED_NUT  = { "火使蜂蜜变硬。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MUSH_MELON  = { "烤过会更好吃。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MUSH_MELON_COOKED  = { "美味的烧焦外皮。", }
	-- Eggs (x5)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.OMELETTE  = { "黄色部分现在很蓬松。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.NOPALITO  = { "一层温暖的仙人掌裹着火焰。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SALAD_EGG  = { "沙拉不能代替煮熟的饭菜。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.EGG_FOO_YUNG  = { "一块酥脆的蛋饼。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MUSHY_EGGS  = { "我不喜欢糊状的食物。", }
	-- Fruits (x4)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.LIMONADE  = { "好冷啊！", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.LIMONGELO  = { "哦，这是果冻。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FRUIT_LEATHER  = { "脱水水果。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FRUIT_TRUFFLE  = { "它甚至没有烹饪过。", }

	-- Ice Recipes (x4)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SOUP_BROTH = { "充其量是温热的。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.JUICE_WATERBERRY = { "多么可怕！", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SOUP_WATERCRESS = { "又湿又软。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TEA_FLORAL = { "至少是温暖的。", }

	-- Ingredients (x5)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.OLEO  = { "就像黄油，但更玉米味。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FLOUR_GROUND = { "就像一堆白色的灰烬。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FRUIT_SYRUP  = { "火焰中提取的甜糖浆。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MOLASSES  = { "令人作呕，但更美味。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.COCONUT_MILK  = { "啊哈！现在你是一种饮料！", }
	-- Liquors (x5+)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.LIQUOR  = { "火水。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MARGARITA  = { "一种冰冻饮料。", } -- Musical Reference "Margaritaville", Jimmy Buffett
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PINA_COLADA  = { "冷冻和甜的。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DAIQUIRI  = { "冷的液体树状物。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.VINO  = { "这种浆果汁让我的肚子变暖。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PINOT_NOIR  = { "陈年浆果汁。", }
	-- Meats (Beef) (x5)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEEF_BUTTER = { "请提交用于检查的引用。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.KIYMALI_PIDE  = { "请提交用于检查的引用。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.COLDCUTS  = { "啊。没有经过火烤的食物？", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BRACIOLE  = { "沐浴在火焰中的多汁卷肉。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEEF_STIRFRY = { "请提交用于检查的引用。", }
	-- Meats (Pork) (x5+)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SAUSAGE_GRAVY  = { "美味的香肠和肉汁。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DUMPLING_PORK  = { "请提交用于检查的引用。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPICED_SAUSAGE  = { "请提交用于检查的引用。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SAUSAGE_COOKED  = { "请提交用于检查的引用。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SAUSAGE_DRIED  = { "请提交用于检查的引用。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPICED_HAM  = { "请提交用于检查的引用。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SWEET_N_SOUR  = { "我喜欢甜的部分。", }

	-- Meats (Seafood) (x3)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.STUFFED_TOMANGO  = { "火焰中烤鱼的外层。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FISH_N_CHIPS  = { "烹饪使它变得酥脆。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SURF_N_TURF  = { "还不错，但可能会更好。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.LOBSTER_FAKED  = { "用假的虫黄色烘烤成棕色。", }
	-- Meats (Poultry) (x3)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ROLLATINI  = { "深火烧烤至肉质饱满。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PICATTA  = { "酸味的烤鸟。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEEFALO_WINGS  = { "肉类待遇加热。", }
	-- Mushrooms (4+)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CITRUS_MUSHROOM  = { "火焰烤制的魔法蘑菇。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MUSHROOM_BURGER  = { "没有番茄酱？", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MUSHROOM_MALODY  = { "火烤使它们变得更糟？", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MUSHROOM_MEDLEY  = { "火烤使它们更美味。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MUSHROOM_STEW  = { "蘑菇在奶油中煮熟。", }
	-- Salads (4)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SALAD_CARROT  = { "我不喜欢沙拉。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SALAD_GRAPE  = { "沙拉并不是那么好吃。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SALAD_WALDORF  = { "至少其中一部分是烹制过的。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SALAD_YAMION  = { "你可以尝到焦蒜的味道。", }	-- Culinary reference: Chard a leafy green vegetable
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SALAD_BLOOM  = { "它们几乎作为食物毫无用处。", }
	-- Soups (x5)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.COLD_GAZPACHO  = { "它冰冷得像冰，但像火一样红。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CACTUS_SOUP  = { "火烤仙人掌泥浆。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SOUP_CHOWDER  = { "鱼肉奶油汤。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GUMBO  = { "我喜欢热汤。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SOUP_SQUASH  = { "美味而热。", }
	-- Snacks (x6 +)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ALOO_TIKI  = { "经火烤硬化的小吃。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CHEESE_LOG  = { "它不会像真正的木柴一样燃烧。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GRUEL  = { "更冷更湿，我越讨厌它。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.NUT_BUTTER  = { "甜味的坚果糊。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PORRIDGE  = { "冷冰冰、湿漉漉的，我讨厌它。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.YAMION_RINGS  = { "让它煎炸，温特勒先生。", }	-- Literary Reference: _Truth_ Terry Pratchett (1948-2015)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TWICE_BAKED  = { "我们能再烤一次吗？", }
	-- Cookables (x4)
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CASSEROLE  = { "有些东西即使火也不能让它更好吃。", }
	-- Crops & Seeds
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GRAPRICOT  = { "不如红色浆果好吃。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GRAPRICOT_COOKED  = { "它们在经过火烤后仍然更好吃。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GRAPRICOT_SEEDS  = { "紫色浆果的种子。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.LIMON  = { "它有一种酸味。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.LIMON_COOKED  = { "它在经过火烤后并没有更好吃？", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.LIMON_SEEDS  = { "酸味水果的种子。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TOMANGO  = { "它的颜色像火一样。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TOMANGO_COOKED  = { "就像火烤过的火一样。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TOMANGO_SEEDS  = { "这些种子可以种出颜色像火一样的水果。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.YAMION  = { "这根植物有奇怪的层次。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.YAMION_COOKED  = { "火把所有的层次都烤熟了。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.YAMION_SEEDS  = { "这些种子会长出层层叠叠的根。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GARLEEK  = { "它的气味让我的眼睛灼痛。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GARLEEK_COOKED  = { "火烤去掉了它的糟糕味道。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ROCKY_MEAT = { "它有一种独特的味道。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ROCKY_MEAT_COOKED= { "烤食物不应该被看作是石头。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TENTACLE_MEAT  = { "它又湿又颤抖。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TENTACLE_MEAT_COOKED  = { "它们尝起来像温暖脆皮的拥抱。", }
	-- Shipwrecked Crops
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PAPAYANAPPLE  = { "在篝火上烹饪非常好。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PAPAYANAPPLE_COOKED  = { "火烤水果。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ZUCCHILLI  = { "植物形态的火焰。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ZUCCHILLI_COOKED  = { "美味的火焰切片。", }
	-- Shipwrecked Crops
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PAPAYANAPPLE  = { "请提交有关检查报价的想法。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PAPAYANAPPLE_COOKED  = { "请提交有关检查报价的想法。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ZUCCHILLI  = { "一个灼热的南瓜。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ZUCCHILLI_COOKED  = { "还是烫手的，但已经不像南瓜了。", }
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ZUCCHILLI_SEEDS  = { "这些种子可以种出辣味南瓜。", }

-- =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+    DESCRIPTIONS.WOLFGANG     =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+

	-- Breads (x4)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SHAMCAKES  = { "为什么面包是扁平的？", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.NANA_BREAD  = { "美味的水果放在面包里。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FRUIT_MUFFIN  = { "小块水果的小面包。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.HARDTACK  = { "味道糟糕，但填饱肚子。", }
	-- Cakes & Pies (x5)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPICED_CAKE  = { "像沃尔夫冈一样强劲。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CACTUS_CAKE  = { "没有冰淇淋？", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MERINGUE  = { "它怎么可以又柔软又硬？", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.STICKY_BUN  = { "都是粘糊糊的。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TARTE_TATIN  = { "软软的蔬菜蛋糕。", }
	-- Candies & Sugars (x5+)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CANDY_SPONGE  = { "看起来像海绵，但坚硬得像石头。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CANDIED_BACON  = { "又酥脆又甜。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CANDIED_FRUIT  = { "被蜜糖包裹的水果。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CANDIED_NUT  = { "脆脆的甜食。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MUSH_MELON  = { "软食物让身体柔软。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MUSH_MELON_COOKED  = { "内部仍然很软。", }
	-- Eggs (x5)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.OMELETTE  = { "松软的食物如何让沃尔夫冈强大？", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.NOPALITO  = { "沃尔夫冈希望没有刺让沃尔夫冈不舒服。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SALAD_EGG  = { "比较好吃的软食物。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.EGG_FOO_YUNG  = { "蔬菜包裹在硬蛋黄里。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MUSHY_EGGS  = { "糊状的蛋无法增长肌肉。", }
	-- Fruits (x4)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.LIMONADE  = { "甜中带酸的饮料。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.LIMONGELO  = { "是松弛的小东西。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FRUIT_LEATHER  = { "水果变得坚韧了。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FRUIT_TRUFFLE  = { "太软太水果味了。", }

	-- Ice Recipes (x4)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SOUP_BROTH = { "浪费肉。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.JUICE_WATERBERRY = { "美味的冰！", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SOUP_WATERCRESS = { "悲伤的绿水。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TEA_FLORAL = { "沃尔夫冈小口喝着杯子里的茶。", }

	-- Ingredients (x5)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.OLEO  = { "很俗，还是有虫子味。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FLOUR_GROUND = { "沃尔夫冈把它磨成了粉末。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FRUIT_SYRUP  = { "太甜了。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MOLASSES  = { "沃尔夫冈对它更加不信任。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COCONUT_MILK  = { "坚硬的壳里面是肌肉饮料。", }
	-- Liquors (x5+)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.LIQUOR  = { "伏特加！", } -- Barrel aged vodka appears brown in color
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MARGARITA  = { "带刺的饮料。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PINA_COLADA  = { "朗姆酒很强劲！", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DAIQUIRI  = { "沃尔夫冈不喜欢冷冻果仁。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.VINO  = { "浓烈的浆果汁。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PINOT_NOIR  = { "非常浓烈的浆果汁。", }
	-- Meats (x5)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEEF_BUTTER = { "请提交审核报价。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.KIYMALI_PIDE  = { "请提交审核报价。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COLDCUTS  = { "冰使肉变得强壮。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BRACIOLE  = { "肉卷里面有软蔬菜。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEEF_STIRFRY = { "请提交审核报价。", }
	-- Meats (Pork) (x5+)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SAUSAGE_GRAVY  = { "在沃尔夫冈的家族中，肉汁是饮料。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DUMPLING_PORK  = { "请提交审核报价。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPICED_SAUSAGE  = { "请提交审核报价。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SAUSAGE_COOKED  = { "请提交审核报价。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SAUSAGE_DRIED  = { "请提交审核报价。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPICED_HAM  = { "请提交审核报价。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SWEET_N_SOUR  = { "加了蜜汁的肉没有那么臭。", }
	-- Meats (Seafood) (x3)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.STUFFED_TOMANGO  = { "现在软蔬菜变得有鱼腥味了。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FISH_N_CHIPS  = { "悲伤的蔬菜看起来有鱼腥味。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SURF_N_TURF  = { "肉看起来有鱼腥味。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.LOBSTER_FAKED  = { "沃尔夫冈现在要吃贝壳怪的爪子了。", }
	-- Meats (Poultry) (x3)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ROLLATINI  = { "肉馅夹着强烈的蔬菜卷。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PICATTA  = { "鸟肉有强烈的酸味。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEEFALO_WINGS  = { "酱料让翅膀变得超级辣。", }
	-- Mushrooms (4+)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CITRUS_MUSHROOM  = { "是果味的糊状食物。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MUSHROOM_BURGER  = { "城里最好吃的汉堡。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MUSHROOM_MALODY  = { "太多蘑菇了。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MUSHROOM_MEDLEY  = { "由各种蘑菇制成。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MUSHROOM_STEW  = { "是一碗好汤。", }
	-- Salads (4)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SALAD_CARROT  = { "稍微好一点，但还是没有肉。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SALAD_GRAPE  = { "稍微好一点的小水果球。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SALAD_WALDORF  = { "现在是沃尔夫冈的沙拉了。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SALAD_YAMION  = { "气味很浓的沙拉。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SALAD_BLOOM  = { "是一份令人愉悦的沙拉。", }
	-- Soups (x5)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COLD_GAZPACHO  = { "味道不错，但是凉了。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CACTUS_SOUP  = { "是最像汤的一种。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SOUP_CHOWDER  = { "汤闻起来有鱼腥味。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GUMBO  = { "所有的东西都放进汤里。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SOUP_SQUASH  = { "懦弱的头全部变成糊状了！", }
	-- Snacks (x7 +)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ALOO_TIKI  = { "原来是软的，现在变成脆的了。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CHEESE_LOG  = { "原木很奶酪味。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.NUT_BUTTER  = { "哈！黄油都是坚果味的！", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PORRIDGE  = { "粘在肚子上。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GRUEL  = { "让我感到恶心。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.YAMION_RING  = { "是舌头的体操环。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TWICE_BAKED  = { "现在不再让我伤心了。", }
	-- Cookables (x4)
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CASSEROLE  = { "食物有第二次成为强大的机会。", }
	-- Crops & Seeds
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GRAPRICOT  = { "软绵绵的小水果球。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GRAPRICOT_COOKED  = { "更软绵绵了。",}
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GRAPRICOT_SEEDS  = { "使水果变成软绵绵的硬种子。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.LIMON  = { "闻起来相当酸。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.LIMON_COOKED  = { "现在闻起来又糊又酸。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.LIMON_SEEDS  = { "小小的酸水果。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TOMANGO  = { "是一个软软的红色蔬菜。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TOMANGO_COOKED  = { "已经煮熟，但还是很软。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TOMANGO_SEEDS  = { "可以变成软蔬菜的种子。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.YAMION  = { "地下蔬菜让我伤心。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.YAMION_COOKED  = { "烤过了，但还是让我伤心。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.YAMION_SEEDS  = { "小小的悲伤蔬菜。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GARLEEK  = { "怎么会有这么强烈的气味？", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GARLEEK_COOKED  = { "强烈的风味。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ROCKY_MEAT = { "很难吃的肉。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ROCKY_MEAT_COOKED= { "一种强大的小吃。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TENTACLE_MEAT  = { "一根细长怪物的尾巴。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TENTACLE_MEAT_COOKED  = { "非常适合零食。", }
	-- Shipwrecked Crops
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PAPAYANAPPLE  = { "奇怪的水果，有坚硬的外壳。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PAPAYANAPPLE_COOKED  = { "坚硬的水果内部变得软绵绵的。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ZUCCHILLI  = { "来自奇怪的南瓜的强烈热量。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ZUCCHILLI_COOKED  = { "切成片的带有强烈热量的南瓜。", }
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ZUCCHILLI_SEEDS  = { "热辣的南瓜被压成小种子。", }


-- =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+    DESCRIPTIONS.WENDY     =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+


	-- Breads (x4)
STRINGS.CHARACTERS.WENDY.DESCRIBE.SHAMCAKES  = { "它们不完全是烙饼。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.NANA_BREAD  = { "热腾腾的香蕉面包。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.FRUIT_MUFFIN  = { "热腾腾的松饼。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.HARDTACK  = { "它们充满了漆黑的绝望味道。", }

	-- Cakes & Pies (x5)
STRINGS.CHARACTERS.WENDY.DESCRIBE.SPICED_CAKE  = { "和我的灵魂一样黑暗。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.CACTUS_CAKE  = { "蛋糕越甜，糖霜越苦。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.MERINGUE  = { "虚无缥缈而美味。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.STICKY_BUN  = { "蜂蜜松饼。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.TARTE_TATIN  = { "一个没有毒的糕点。", }
	-- Candies & Sugars (x5+)
STRINGS.CHARACTERS.WENDY.DESCRIBE.CANDY_SPONGE  = { "充满孔洞，就像我的内心。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.CANDIED_BACON  = { "甜而美味的条状食物。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.CANDIED_FRUIT  = { "甜，但又凌乱又粘。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.CANDIED_NUT  = { "树木的甜蜜死亡。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.MUSH_MELON  = { "甜蜜的糊状蜜瓜。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.MUSH_MELON_COOKED  = { "火使它变得美味。", }
	-- Eggs (x5)
STRINGS.CHARACTERS.WENDY.DESCRIBE.OMELETTE  = { "搅打和击败。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.NOPALITO  = { "营养丰富的蛋和仙人掌束。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.SALAD_EGG  = { "一团忧郁的压成糊状物...带有蛋黄酱。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.EGG_FOO_YUNG  = { "这是我的痛苦灵魂。", } -- The name comes from Cantonese language
STRINGS.CHARACTERS.WENDY.DESCRIBE.MUSHY_EGGS  = { "所有的希望都被搅成糊状。", }
	-- Fruits (x4)
STRINGS.CHARACTERS.WENDY.DESCRIBE.LIMONADE  = { "冰凉的苦甜口感。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.LIMONGELO  = { "果肉悬浮在如梦如幻的果冻中。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.FRUIT_LEATHER  = { "脱水水果。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.FRUIT_TRUFFLE  = { "一个不太重要的水果盘。", }

	-- Ice Recipes (x4)
STRINGS.CHARACTERS.WENDY.DESCRIBE.SOUP_BROTH = { "甜美的恐惧香气。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.JUICE_WATERBERRY = { "冻酸味的尖锐咬感。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.SOUP_WATERCRESS = { "一种辛辣的汤。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.TEA_FLORAL = { "阿比盖尔会喜欢这个的。", }

	-- Ingredients (x5)
STRINGS.CHARACTERS.WENDY.DESCRIBE.OLEO  = { "我应该预料到这一点。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.FLOUR_GROUND  = { "最终，我们都会变成尘土。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.FRUIT_SYRUP  = { "浓缩的水果精华。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.MOLASSES  = { "黑色糖浆的样本。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.COCONUT_MILK  = { "它是整个的，还是一半和一半的？", }
	-- Liquors (x5+)
STRINGS.CHARACTERS.WENDY.DESCRIBE.LIQUOR  = { "苦艾酒的味道。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.MARGARITA  = { "我会渐渐消失。", } -- musical reference "Margaritaville", Jimmy Buffett
STRINGS.CHARACTERS.WENDY.DESCRIBE.DAIQUIRI  = { "没有什么能像朗姆酒一样平静心灵。", } -- "There's naught, no doubt, so much the spirit calms as rum and true religion." - Lord Byron
STRINGS.CHARACTERS.WENDY.DESCRIBE.PINA_COLADA  = { "我承认我喜欢椰子酒。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.VINO  = { "有些葡萄酒随着时间变成了醋。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.PINOT_NOIR  = { "年轻的葡萄酒的失落年华更加甜美。", }
	-- Meats (Beef) (x5)
STRINGS.CHARACTERS.WENDY.DESCRIBE.BEEF_BUTTER = { "请提交想法供审核。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.KIYMALI_PIDE  = { "请提交想法供审核。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.COLDCUTS  = { "冰冻的残骸。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.BRACIOLE  = { "一顿在肉的包裹下的餐。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.BEEF_STIRFRY = { "请提交想法供审核。", }
	-- Meats (Pork) (x5+)
STRINGS.CHARACTERS.WENDY.DESCRIBE.SAUSAGE_GRAVY  = { "浓郁的酱汁覆盖着塞满的内脏。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.DUMPLING_PORK  = { "请提交想法供审核。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.SPICED_SAUSAGE  = { "请提交想法供审核。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.SAUSAGE_COOKED  = { "请提交想法供审核。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.SAUSAGE_DRIED  = { "请提交想法供审核。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.SPICED_HAM  = { "请提交想法供审核。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.SWEET_N_SOUR  = { "酸甜如生与死一般。", }
	-- Meats (Seafood) (x3)
STRINGS.CHARACTERS.WENDY.DESCRIBE.STUFFED_TOMANGO  = { "我将其称之为鱼类植物。", } -- French- Poisson Plante: Fish Plant
STRINGS.CHARACTERS.WENDY.DESCRIBE.SURF_N_TURF  = { "两次尝过死亡，以滋养我。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.FISH_N_CHIPS  = { "它在炸油中游泳，充满悲伤。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.LOBSTER_FAKED  = { "它曾在烤箱的热量中晒过太阳。", }
	-- Meats (Poultry) (x3)
STRINGS.CHARACTERS.WENDY.DESCRIBE.ROLLATINI  = { "一顿裹在蔬菜寿衣中的餐。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.PICATTA  = { "浸泡在苦涩中。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.BEEFALO_WINGS  = { "夜生物的热量。", }
	-- Mushrooms (4+)
STRINGS.CHARACTERS.WENDY.DESCRIBE.CITRUS_MUSHROOM  = { "发霉、潮湿、湿漉漉、酸味。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.MUSHROOM_BURGER  = { "可塑的肉和蘑菇。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.MUSHROOM_MALODY  = { "令人失望的单调。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.MUSHROOM_MEDLEY  = { "无尽的可塑性。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.MUSHROOM_STEW  = { "奶油汁蘑菇。", }
	-- Salads (4)
STRINGS.CHARACTERS.WENDY.DESCRIBE.SALAD_CARROT  = { "这是根蔬菜浸泡在甜果汁中。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.SALAD_GRAPE  = { "这绝对不是一碗樱桃。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.SALAD_WALDORF  = { "煮熟的肉拌入微小的蔬菜海洋中。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.SALAD_YAMION  = { "一份悲伤的沙拉。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.SALAD_BLOOM  = { "恶是生活沙拉的苦涩。", }
	-- Soups (x5)
STRINGS.CHARACTERS.WENDY.DESCRIBE.COLD_GAZPACHO  = { "像坟墓一样冷。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.CACTUS_SOUP  = { "刺已经被煮掉了。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.SOUP_CHOWDER  = { "在奶油中煮沸可以阻止鱼肉松脆。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.GUMBO  = { "一种辛辣的食物混合物。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.SOUP_SQUASH  = { "浓郁的黄油糊状物。", }
	-- Snacks (x7 +)
STRINGS.CHARACTERS.WENDY.DESCRIBE.ALOO_TIKI  = { "悲伤的苏麦小吃。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.CHEESE_LOG  = { "用原木形状的凝乳制成的食物。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.NUT_BUTTER  = { "更加令人意外。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.PORRIDGE  = { "湿漉漉又凉的粥。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.GRUEL  = { "湿漉漉又非常冷的稀粥。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.POPCORN_BUTTERY = { "我喜欢在黑暗中吃爆米花。", } -- Charles Bukowski on why he goes to the movies
STRINGS.CHARACTERS.WENDY.DESCRIBE.YAMION_RINGS  = { "悲伤的圆环裹着油炸糊。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.TWICE_BAKED  = { "烤过的悲伤层层叠叠，浇上热黄油。", }
	-- Cookables (x4)
STRINGS.CHARACTERS.WENDY.DESCRIBE.CASSEROLE  = { "剩菜得到了重新成为食物的机会。", }
	-- Crops & Seeds
STRINGS.CHARACTERS.WENDY.DESCRIBE.GRAPRICOT  = { "软绵绵的水果，有坚硬的果核。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.GRAPRICOT_COOKED  = { "没有果核更好。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.GRAPRICOT_SEEDS  = { "只是一个种子。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.LIMON  = { "两面都酸。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.LIMON_COOKED  = { "我觉得它不应该这样烹饪。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.LIMON_SEEDS  = { "是的，这就是种子的样子。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.TOMANGO  = { "它与毒漆树有关，但它并不是毒品。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.TOMANGO_COOKED  = { "可悲的是，烹饪后它仍然不会有毒。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.TOMANGO_SEEDS  = { "毒漆树的种子。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.YAMION  = { "它让我想哭。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.YAMION_COOKED  = { "层层烤制的悲伤。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.YAMION_SEEDS  = { "悲伤的种子。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.GARLEEK  = { "它有一种悲伤而辛辣的气味。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.GARLEEK_COOKED  = { "如此浓烈的风味。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.ROCKY_MEAT = { "不幸的结束。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.ROCKY_MEAT_COOKED= { "麻烦很多，气泡很多。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.TENTACLE_MEAT  = { "又细又苍白，湿湿滑滑的。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.TENTACLE_MEAT_COOKED  = { "脆脆的咸悲伤圈。", }
	-- Shipwrecked Crops
STRINGS.CHARACTERS.WENDY.DESCRIBE.PAPAYANAPPLE  = { "请提交想法供审查的引用。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.PAPAYANAPPLE_COOKED  = { "请提交想法供审查的引用。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.ZUCCHILLI  = { "燃烧孤寂的南瓜。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.ZUCCHILLI_COOKED  = { "燃烧孤寂，在炭火上烤制而成。", }
STRINGS.CHARACTERS.WENDY.DESCRIBE.ZUCCHILLI_SEEDS  = { "燃烧孤寂包装在孤独的种子中。", }


-- =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+    DESCRIPTIONS.WICKERBOTTOM     =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+


	-- Breads (x4)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SHAMCAKES  = { "在苏格兰，这被称为小煎饼。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.NANA_BREAD  = { "一种湿润、甜美、像蛋糕一样的快速面包。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FRUIT_MUFFIN  = { "一种小巧、甜美、像蛋糕一样的面包松饼。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.HARDTACK  = { "在没有其他易腐食物的情况下，可以长时间保存的食物。", }

	-- Cakes & Pies (x5)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPICED_CAKE  = { "美味而奢华的香料。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CACTUS_CAKE  = { "你想要吃蛋糕吗？", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MERINGUE  = { "意大利蛋白霜是用糖浆和蛋白制成的。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.STICKY_BUN  = { "肉桂是从树皮中提取的。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TARTE_TATIN  = { "一种在烘烤前先焦糖化的倒扣糕点。", }
	-- Candies & Sugars (x5+)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CANDY_SPONGE  = { "轻盈脆爽的太妃糖。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CANDIED_BACON  = { "裹着太妃糖的培根，提供咸甜的小吃。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CANDIED_FRUIT  = { "水果被浓稠粘稠的糖浆保存。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CANDIED_NUT  = { "种子被结晶糖包裹。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MUSH_MELON  = { "这不是一个正式的食谱。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MUSH_MELON_COOKED  = { "外皮已经焦糖化。", }
	-- Eggs (x5)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.OMELETTE  = { "蛋的有效利用方式。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.NOPALITO  = { "Nopalito是由仙人掌嫩叶制成的。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SALAD_EGG  = { "种类包括鸡肉、火腿和金枪鱼沙拉。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.EGG_FOO_YUNG  = { "字面意思是'芙蓉蛋'。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MUSHY_EGGS  = { "蛋的适当利用方式。", }
	-- Fruits (x4)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LIMONADE  = { "保持凉爽的标准饮品。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LIMONGELO  = { "琼脂是一种在藻类中发现的胶状物质。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FRUIT_LEATHER  = { "柑橘汁有助于保存它。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FRUIT_TRUFFLE  = { "一种琐碎的水果甜点。", }

	-- Ice Recipes (x4)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SOUP_BROTH = { "一种由煮熟的肉制成的可口液体。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.JUICE_WATERBERRY = { "冰和水果的混合物。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SOUP_WATERCRESS = { "一种煮沸的蔬菜汤。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEA_FLORAL = { "植物材料在热水中煎煮的饮料。", }

	-- Ingredients (x5)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.OLEO  = { "昆虫乳化剂？", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FLOUR_GROUND = { "坚果和种子制成的低碳水化合物面粉。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FRUIT_SYRUP  = { "古罗马人用水果浓缩物来甜化葡萄酒。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MOLASSES  = { "一些文化使用石榴制作糖蜜。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COCONUT_MILK  = { "从椰子肉中提取的液体。", }
	-- Liquors (x5+)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LIQUOR  = { "一点白兰地。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MARGARITA  = { "龙舌兰和柑橘的混合物。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PINA_COLADA  = { "椰子奶油和朗姆酒的混合物。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DAIQUIRI  = { "Mi daiquiri en El Floridita。", } -- A quote attributed to Ernest Hemingway, though like untrue
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.VINO  = { "随着时间的推移，它只会变得更好。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PINOT_NOIR  = { "经过完美陈酿的红葡萄酒。", }
	-- Meats (Beef) (x5)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEEF_BUTTER = { "请提交想法以供检查报价。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KIYMALI_PIDE  = { "请提交想法以供检查报价。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COLDCUTS  = { "切片肉包裹在冰中。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BRACIOLE  = { "卷起的肉片，内部填有多种食材。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEEF_STIRFRY = { "秘密在于用少量非常热的油翻炒。", }
	-- Meats (Pork) (x5+)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SAUSAGE_GRAVY  = { "咸肉和用肉汁制成的白色酱。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DUMPLING_PORK  = { "请提交想法以供检查报价。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPICED_SAUSAGE  = { "请提交想法以供检查报价。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SAUSAGE_COOKED  = { "请提交想法以供检查报价。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SAUSAGE_DRIED  = { "请提交想法以供检查报价。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPICED_HAM  = { "请提交想法以供检查报价。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SWEET_N_SOUR  = { "酱汁是蜂蜜和酸味植物的混合物。", }
	-- Meats (Seafood) (x3)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.STUFFED_TOMANGO  = { "将切碎的鱼肉塞入蔬菜壳中。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SURF_N_TURF  = { "烤海鲜和丰盛的牛排。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FISH_N_CHIPS  = { "英国工人阶级中常见的一餐。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LOBSTER_FAKED  = { "通常使用干热烘烤。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SLURRY_SEAFOOD  = { "一种混杂的鱼肉菜肴。", }
	-- Meats (Poultry) (x3)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ROLLATINI  = { "薄片肉涂上调味料，然后卷起来烤。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PICATTA  = { "切片，裹上面衣，煎炒，然后用柑橘酱汁上桌。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEEFALO_WINGS  = { "这些小翅膀会加重我的消化不良。", }
	-- Mushrooms (4+)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CITRUS_MUSHROOM  = { "用大蒜腌制过夜，可以获得良好的风味。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MUSHROOM_BURGER  = { "肉馅饼形式的肉loaf。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MUSHROOM_MALODY  = { "毒性成分已被复合。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MUSHROOM_MEDLEY  = { "最好的品质经过提炼和纯化。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MUSHROOM_STEW  = { "蘑菇在基础稀薄的白汁中煮熟。", }
	-- Salads (4)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SALAD_CARROT  = { "配上甜柠檬醋汁。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SALAD_GRAPE  = { "一道老式的甜奶油沙拉。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SALAD_WALDORF  = { "17世纪在华尔道夫酒店首创。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SALAD_YAMION  = { "富含抗氧化剂、维生素C和钾。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SALAD_BLOOM  = { "花朵烹饪可以追溯到罗马时代。", }
	-- Soups (x5)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COLD_GAZPACHO  = { "由生蔬菜制成，冷食。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CACTUS_SOUP  = { "仙人掌茎非常多汁。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SOUP_CHOWDER  = { "通常与脆饼干一起食用。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GUMBO  = { "用鱼和蔬菜调味的浓郁高汤。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SOUP_SQUASH  = { "它有一种甜味和坚果味。", }
	-- Snacks (x7 +)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ALOO_TIKI  = { "一个小食物卷成圆柱形，然后油炸。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CHEESE_LOG  = { "它让我想起了牛犊蛋。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.NUT_BUTTER  = { "主要由研磨烘烤的坚果制成的食品糊。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PORRIDGE  = { "煮熟的碾碎谷物加入调味料。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GRUEL  = { "煮熟的碾碎谷物，没有味道。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.YAMION_RINGS  = { "油炸的鳞茎横切片。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TWICE_BAKED  = { "内部已被挖空，混合后重新烘烤。", }
	-- Spiced (x5 +1)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SALAD_SPICED  = { "有许多种类的泰式沙拉。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPICED_FISH = { "一道用海鲜制作的东方炖菜。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPICED_RUM  = { "一口饮料会扩张你的血管，虚假地让你感觉皮肤温暖。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DRAGON_ROLL  = { "传统上应该使用牛油果代替火龙果。", }
	-- Cookables (x4)
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CASSEROLE  = { "法国厨师会做一个这样的盒子。", }
	-- Crops & Seeds
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GRAPRICOT  = { "它们有一种苦味，来自苹果酸。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GRAPRICOT_COOKED  = { "苹果酸在加热时可以转化为柠檬酸。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GRAPRICOT_SEEDS  = { "果核在技术上只是种子的外壳。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LIMON  = { "柑橘品种柠檬有一种非常酸和苦的味道。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LIMON_COOKED  = { "柑橘品种柠檬有多种烹饪用途。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LIMON_SEEDS  = { "某些柑橘品种的柠檬是无籽的。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TOMANGO  = { "技术上是水果，但通常被视为蔬菜。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TOMANGO_COOKED  = { "美味的炸金果。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TOMANGO_SEEDS  = { "金果的种子相对较大。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.YAMION  = { "它们含有产生刺激眼睛的气体的酶。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.YAMION_COOKED  = { "洋葱属植物的一些品种包括葱和土豆洋葱。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.YAMION_SEEDS  = { "这些是植物种子，与种薯区分开来。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GARLEEK  = { "它的压倒性气味使其非常不好吃。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GARLEEK_COOKED  = { "辛辣刺激的味道适合调味。", }
	-- Shipwrecked Crops
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PAPAYANAPPLE  = { "请提交对考察报告的想法。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PAPAYANAPPLE_COOKED  = { "请提交对考察报告的想法。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ZUCCHILLI  = { "请提交对考察报告的想法。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ZUCCHILLI_COOKED  = { "请提交对考察报告的想法。", }
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ZUCCHILLI_SEEDS  = { "种子是最强烈的辣椒热量来源。", }



-- =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+    DESCRIPTIONS.WAXWELL     =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+


	-- Breads (x4)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SHAMCAKES  = { "你把这些叫蛋糕？它们只不过是个骗局而已。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.NANA_BREAD  = { "我猜它应该比之前的好吃一些。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FRUIT_MUFFIN  = { "我更喜欢罂粟籽松饼。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.HARDTACK  = { "事情真的这么糟糕吗，让我不得不吃这些东西？", }

	-- Cakes & Pies (x5)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPICED_CAKE  = { "带有奶油糖霜的可怕蛋糕。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CACTUS_CAKE  = { "蛋糕是个谎言。", } -- reference to game 'Portal'
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MERINGUE  = { "派也是个谎言。", } -- reference to game 'Portal'
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.STICKY_BUN  = { "真让人惊讶这个面包里没有兔子。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TARTE_TATIN  = { "缺乏酸味。", }
	-- Candies & Sugars (x5+)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CANDY_SPONGE  = { "这个糖就像这个世界的类比。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CANDIED_BACON  = { "一种脆脆的家乡味道。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CANDIED_FRUIT  = { "太多的甜蜜让我感到恶心。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CANDIED_NUT  = { "带有糖衣的种子。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MUSH_MELON  = { "显然有人喜欢双关语。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MUSH_MELON_COOKED  = { "我不能反驳传统。", }
	-- Eggs (x5)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.OMELETTE  = { "终于！一道真正高雅的菜肴。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.NOPALITO  = { "我更喜欢一些更高雅的东西。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SALAD_EGG  = { "一道平淡无奇的中产阶级菜肴。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.EGG_FOO_YUNG  = { "看起来很外国。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MUSHY_EGGS  = { "我几乎宁愿生吃。", }
	-- Fruits (x4)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.LIMONADE  = { "“当生活给你柠檬时...”", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.LIMONGELO  = { "现在果实也被困住了。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FRUIT_LEATHER  = { "水果的肉干。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FRUIT_TRUFFLE  = { "水果的层次并不重要。", }

	-- Ice Recipes (x4)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SOUP_BROTH = { "我真的堕落到这个地步了吗。", } -- pun : In cooking, reduction is intensifying the flavor of a liquid mixture
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.JUICE_WATERBERRY = { "奇怪的清爽。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SOUP_WATERCRESS = { "一种滋养但是不浓的汤。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TEA_FLORAL = { "Wickerbottom小姐可能会喜欢这个。", }

	-- Ingredients (x5)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.OLEO  = { "一种劣质的替代品，无法与真正的黄油媲美。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FLOUR_GROUND = { "一种劣质的烘焙材料。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FRUIT_SYRUP  = { "蒸馏过的果汁。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MOLASSES  = { "哦。不。不，这太过分了。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COCONUT_MILK  = { "我更喜欢浓郁的奶油。", }
	-- Liquor (x5+)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.LIQUOR  = { "一杯美好的干邑。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MARGARITA  = { "当生活给你柠檬时，就做玛格丽特吧。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PINA_COLADA  = { "就像海洋的感觉和香槟的味道一样。", } -- Musical Reference "Escape (Pina Colada song)", Rupert Holmes 
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DAIQUIRI  = { "我想我提前几十年发明了戴奇里鸡尾酒。", } 
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.VINO  = { "葡萄酒是世界上最文明的东西之一。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PINT_NOIR  = { "陈年的葡萄酒是世界上最文明的东西之一。", }
	-- Meats (Beef) (x5)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEEF_BUTTER = { "请提交对报考题目的想法。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.KIYMALI_PIDE  = { "请提交对报考题目的想法。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COLDCUTS  = { "这是最糟糕的。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BRACIOLE  = { "这些通常保留给第二道菜。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEEF_STIRFRY = { "请提交对报考题目的想法。", }
	-- Meats (Pork) (x5+)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SAUSAGE_GRAVY  = { "在油腻的酱汁中塞满内脏。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DUMPLING_PORK  = { "请提交对报考题目的想法。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPICED_SAUSAGE  = { "请提交对报考题目的想法。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SAUSAGE_COOKED  = { "请提交对报考题目的想法。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SAUSAGE_DRIED  = { "请提交对报考题目的想法。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPICED_HAM  = { "请提交对报考题目的想法。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SWEET_N_SOUR  = { "我想这是可以吃的。", }

	-- Meats (x4)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEEF_MAXWELL = { "威灵顿公爵给了我这个食谱。", } -- Arthur Wellesley : First Duke of Wellington
-- Meats (Seafood) (x3)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.STUFFED_TOMANGO  = { "优雅的巅峰之作。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SURF_N_TURF  = { "适合我的一顿饭。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FISH_N_CHIPS  = { "地道的家乡味道。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.LOBSTER_FAKED  = { "我不知道食谱，但我可以假装。", }
	-- Meats (Poultry) (x3)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ROLLATINI  = { "不太优雅，但可以吃。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PICATTA  = { "用小牛肉做的更好。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEEFALO_WINGS  = { "名字并不能欺骗任何人。", }
	-- Mushrooms (4+)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CITRUS_MUSHROOM  = { "把食物放在棍子上永远没有尽头吗？", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MUSHROOM_BURGER  = { "约翰·蒙塔古会为之自豪。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MUSHROOM_MALODY  = { "出了点问题。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MUSHROOM_MEDLEY  = { "一个家传秘方。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MUSHROOM_STEW  = { "炖蘑菇。", }
	-- Salads (4)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SALAD_CARROT  = { "现在这是一种精致的根。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SALAD_GRAPE  = { "我曾在晚宴上吃过这道菜。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SALAD_WALDORF  = { "我应该把Waldorf请到这里做我的私人厨师。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SALAD_YAMION  = { "可能更有营养。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SALAD_BLOOM  = { "它有一种美丽的味道。", }
	-- Soups (x5)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COLD_GAZPACHO  = { "夏日炎炎中的清凉口感。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CACTUS_SOUP  = { "这种仙人掌令人惊讶地多用途。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SOUP_CHOWDER  = { "这需要牡蛎饼干。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GUMBO  = { "粗糙的辣炖菜。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SOUP_SQUASH  = { "一种优雅的美味浓汤。", }
	-- Snacks (x6 +)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ALOO_TIKI  = { "请告诉我这里没有脆生的青蛙。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CHEESE_LOG  = { "现在我只需要一些葡萄酒。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.NUT_BUTTER  = { "纯粹邪恶的食谱。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PORRIDGE  = { "比湿泥稍微好一些的选择。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GRUEL  = { "湿泥的悲伤替代品。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.YAMION_RINGS  = { "统治它们所有的山葱戒指。", } -- literary reference 'One ring to rule them all...' - J.R.R. Tolkien
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TWICE_BAKED  = { "相当美味的各种馅料。", }
	-- Cookables (x4)
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CASSEROLE  = { "没有人真正知道这些东西里面有什么。", }
	-- Crops & Seeds
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GRAPRICOT  = { "不是一碗樱桃。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GRAPRICOT_COOKED  = { "至少稍微精致了一点。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GRAPRICOT_SEEDS  = { "这样的劳动对我来说太低级了。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.LIMON  = { "柑橘风味的混合。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.LIMON_COOKED  = { "我更喜欢柠檬的味道。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.LIMON_SEEDS  = { "这样的劳动对我来说太低级了。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TOMANGO  = { "显然是水果。" }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TOMANGO_COOKED  = { "至少稍微精致了一点。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TOMANGO_SEEDS  = { "这样的劳动对我来说太低级了。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.YAMION  = { "它的气味几乎足以把死人叫醒。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.YAMION_COOKED  = { "就像街头小贩卖的烤土豆。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.YAMION_SEEDS  = { "这样的劳动对我来说太低级了。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GARLEEK  = { "这闻起来比尝起来更好...而且它闻起来很糟糕。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GARLEEK_COOKED  = { "至少烹饪之后不再有气味了。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ROCKY_MEAT = { "那就是这个东西的结局了。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ROCKY_MEAT_COOKED= { "这个配上面包卷会更好。", } -- pun Lobster Roll / Rock and Roll
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TENTACLE_MEAT  = { "看起来好像被砍掉一小块。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TENTACLE_MEAT_COOKED  = { "至少现在它不再动了。", }
	-- Shipwrecked Crops
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PAPAYANAPPLE  = { "请提交想法进行审查报价。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PAPAYANAPPLE_COOKED  = { "请提交想法进行审查报价。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ZUCCHILLI  = { "请提交想法进行审查报价。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ZUCCHILLI_COOKED  = { "请提交想法进行审查报价。", }
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ZUCCHILLI_SEEDS  = { "请提交想法进行审查报价。", }


-- =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+    DESCRIPTIONS.WATHGRITHR     =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+

	
	-- Breads (x4)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SHAMCAKES = { "这对于一个战士来说不合适。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.NANA_BREAD = { "一块猴子食物。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FRUIT_MUFFIN = { "松饼里什么都没有。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.HARDTACK = { "干燥无味，绝对没有肉。", }

	-- Cakes & Pies (x5)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPICED_CAKE  = { "黑暗而邪恶的诱惑。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CACTUS_CAKE = { "我不太喜欢蛋糕。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MERINGUE = { "浪费了好的鸡蛋。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.STICKY_BUN = { "我会坚持吃肉。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TARTE_TATIN = { "太可惜不是个肉派。", }
	-- Candies & Sugars (x5+)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CANDY_SPONGE  = { "洞洞蛋糕，我不会拒绝。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CANDIED_BACON = { "甜蜜与肉的结合。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CANDIED_FRUIT = { "我更喜欢甜面包。", } -- Sweetbread : a culinary term for the thymus or neck
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CANDIED_NUT = { "我更喜欢甜面包。", } -- Sweetbread : a culinary term for the thymus or neck
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MUSH_MELON = { "烤着吃和品尝不错。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MUSH_MELON_COOKED = { "我喜欢串起来吃。", }
	-- Eggs (x5)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.OMELETTE = { "现在吃蛋。", }  -- Old Norse- Eggja : to sharpen
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.NOPALITO = { "剑植物和热蛋。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SALAD_EGG = { "这真的是沙拉吗？", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.EGG_FOO_YUNG  = { "傻瓜。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MUSHY_EGGS = { "激发了我的食欲。", }-- Norwegian- Egger : to incite
	-- Fruits (x4)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.LIMONADE = { "我对此感觉不好。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.LIMONGELO = { "它在动，但它不是活的。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FRUIT_LEATHER = { "它不是真正的皮革。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FRUIT_TRUFFLE = { "完全无关紧要。", } -- Trifle : something of little importance

	-- Ice Recipes (x4)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SOUP_BROTH = { "一种液体小吃。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.JUICE_WATERBERRY = { "看着它就让我的大脑疼。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SOUP_WATERCRESS = { "一点肉也没有。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TEA_FLORAL = { "这种饮品不适合战士。", }

	-- Ingredients (x5)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.OLEO = { "在战斗中，它会被黄油打败。" } -- Literary reference: "Butter Battle Book" : by Doctor Seuss
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FLOUR_GROUND = { "高蛋白质，但没有肉。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FRUIT_SYRUP = { "也许加上肉会更好吃。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MOLASSES = { "非常甜，但仍然不是肉。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.COCONUT_MILK  = { "椰子的生命之源。", }
	-- Liquor (x5 +1)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.LIQUOR = { "一杯蜜酒，不是肉。" } -- Mead : An alcoholic beverage
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DAIQUIRI = { "我并不是很喜欢它。", } 
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MARGARITA = { "我不知道原因。" } -- Musical Reference "Margaritaville", Jimmy Buffett
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PINA_COLADA = { "我对健康食品并不感兴趣。" } -- Musical Reference "Escape (Pina Colada song)", Rupert Holmes 
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.VINO = { "葡萄酒只是葡萄汁。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PINT_NOIR = { "陈年的葡萄酒只是老的葡萄汁。", }
	-- Meats (Beef) (x5)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEEF_BUTTER = { "请提交关于此引文的创意。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.KIYMALI_PIDE  = { "请提交关于此引文的创意。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.COLDCUTS = { "冰上的预熟肉。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BRACIOLE = { "肉包裹的蔬菜。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEEF_STIRFRY = { "请提交关于此引文的创意。", } 
	-- Meats (Pork) (x5+)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SAUSAGE_GRAVY = { "我喜欢香肠，其他只是调味汁。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DUMPLING_PORK  = { "请提交关于此引文的创意。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPICED_SAUSAGE  = { "请提交关于此引文的创意。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SAUSAGE_COOKED  = { "请提交关于此引文的创意。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SAUSAGE_DRIED  = { "请提交关于此引文的创意。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPICED_HAM  = { "请提交关于此引文的创意。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SWEET_N_SOUR = { "它尝起来像胜利。", }
	-- Meats (Seafood) (x3)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SURF_N_TURF = { "一顿饭中两倍的肉。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FISH_N_CHIPS = { "鱼肉和切碎的根茎。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.STUFFED_TOMANGO = { "我想这也算是肉。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.LOBSTER_FAKED = { "如果在黄油之战中胜出，它会更好吃。", } -- Literary reference: "Butter Battle Book" : by Doctor Seuss
	-- Meats (Poultry) (x3)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ROLLATINI = { "肉包裹的蔬菜。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PICATTA = { "有趣的味道。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEEFALO_WINGS = { "啊！一只牛翅膀！", } -- Anagram of "Beefalo wing"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SALAD_WALDORF = { "如果里面有肉，那还算是沙拉吗？", }
	-- Mushrooms (4+)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CITRUS_MUSHROOM = { "恶心的蘑菇和恶心的水果在一根矛上。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MUSHROOM_BURGER = { "蘑菇夹着肉。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MUSHROOM_MALODY = { "色彩缤纷，但我还是不会吃。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MUSHROOM_MEDLEY = { "色彩缤纷，但我不会吃。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MUSHROOM_STEW = { "恶心的蘑菇漂浮在奶油中。", }
	-- Salads (4)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SALAD_CARROT = { "看不到一丝肉。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SALAD_GRAPE = { "没有肉就没有理由称其为食物。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SALAD_YAMION = { "不。我不会去吃那个。", } -- An onion is a type of leek 
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SALAD_BLOOM = { "不知怎么回事，这似乎连肉都更少了。", }
	-- Soups (x5)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GAZPACHO = { "加斯帕乔（Gazpach-no）。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CACTUS_SOUP = { "剑植物汤。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SOUP_CHOWDER = { "鱼肉在奶油中炖煮。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GUMBO = { "辛辣的鱼肉炖菜。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SOUP_SQUASH = { "我必须发疯才会吃那个。", } -- pmpkin and squash are types of gourd
	-- Snacks (x7 +)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ALOO_TIKI = { "如果用肉填充会很好吃。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CHEESE_LOG = { "我绝不会吃那个。", } -- Whey : A liquid byproduct of making cheese
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.NUT_BUTTER = { "甜味的坚果肉。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PORRIDGE = { "这是不可食用的稠糊。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GRUEL = { "这是不可食用的稀粥。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.YAMION_RINGS = { "蔬菜圈在油中炸。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TWICE_BAKED = { "我不确定里面有足够的肉。", }
	-- Cookables (x4)
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CASSEROLE = { "里面有肉。但那是肉吗？", }
	-- Crops & Seeds
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GRAPRICOT = { "水果球。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GRAPRICOT_COOKED = { "炖水果球。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GRAPRICOT_SEEDS = { "微小的自然物质。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.LIMON = { "有趣，但我不喜欢水果。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.LIMON_COOKED = { "我仍然不喜欢水果。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.LIMON_SEEDS = { "微小的自然物质。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TOMANGO = { "它可能做成很好的酱。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TOMANGO_COOKED = { "我不喜欢蔬菜...或水果...或蔬菜。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TOMANGO_SEEDS = { "微小的自然物质。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.YAMION = { "加点肉或鱼可能会好吃。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.YAMION_COOKED = { "气味是一个强大的敌人。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.YAMION_SEEDS = { "微小的自然物质。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GARLEEK = { "浓烈的味道可以给许多肉类菜肴增添香气。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GARLEEK_COOKED = { "为一些肉类或鱼类添加的好东西。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ROCKY_MEAT = { "今晚我会吃得很好。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ROCKY_MEAT_COOKED= { "这会加上一块面包更好。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TENTACLE_MEAT  = { "一块黏黏的肉。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TENTACLE_MEAT_COOKED  = { "一种凶残的味道。", }
	-- Shipwrecked Crops
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PAPAYANAPPLE = { "装甲水果。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PAPAYANAPPLE_COOKED = { "被击败的水果。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ZUCCHILLI = { "请提交对检查报价的想法。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ZUCCHILLI_COOKED = { "请提交对检查报价的想法。", }
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ZUCCHILLI_SEEDS = { "微小的自然物质。", }


-- =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+    DESCRIPTIONS.WEBBER     =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+


	-- Breads (x3)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SHAMCAKES = { "浆果就像眼睛。它们让我起鸡皮疙瘩！", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.NANA_BREAD = { "一堆面包。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.FRUIT_MUFFIN = { "一个浆果味的面包。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.HARDTACK = { "它们在我们的嘴里留下一股煤烟味。", }

	-- Cakes & Pies (x5)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SPICED_CAKE  = { "它闻起来像我们的小朋友。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CACTUS_CAKE = { "相当刺人。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MERINGUE = { "饼上的烤蛋。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.STICKY_BUN = { "我们应该坚守我们的饮食吗？", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TARTE_TATIN = { "蔬菜派？", }
	-- Candies & Sugars (x5+)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CANDY_SPONGE  = { "一个不一样的洞洞糖！", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CANDIED_BACON = { "黄油、糖和盐的小吃。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CANDIED_FRUIT = { "我们觉得它可能太甜了。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CANDIED_NUT = { "上了糖衣的坚果。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MUSH_MELON = { "爷爷会在我们去露营时烤这些。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MUSH_MELON_COOKED = { "烤成了金黄色。", }
	-- Eggs (x5)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.OMELETTE = { "里面装满了美味的食物。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.NOPALITO = { "带着刺的蛋。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SALAD_EGG = { "妈妈每周都会做这个。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.EGG_FOO_YUNG = { "就像过熟的煎蛋饼。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MUSHY_EGGS = { "一团糊状物，就像爸爸做的那样。", }
	-- Fruits (x4)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.LIMONADE = { "爷爷会在夏天和我一起喝这个。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.LIMONGELO = { "我们可以整天看它颤动。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.FRUIT_LEATHER = { "嚼劲十足的水果条。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.FRUIT_TRUFFLE = { "蛋糕、水果和布丁。", } -- Fruit Trifle : A desert of layered fruit, cake, pudding, and whipped cream

	-- Ice Recipes (x4)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SOUP_BROTH = { "味道像咸水。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.JUICE_WATERBERRY = { "如果它是锥形的就好了。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SOUP_WATERCRESS = { "液体蔬菜。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TEA_FLORAL = { "妈妈会加蜂蜜进去。", }

	-- Ingredients (x5)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.OLEO = { "这是一种人造黄油。", } -- oleo is another name for margarine
STRINGS.CHARACTERS.WEBBER.DESCRIBE.FLOUR_GROUND = { "一种相当不错的物质。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.FRUIT_SYRUP = { "水果的精华液。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MOLASSES = { "爷爷说：“你打赌这是好东西。”", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.COCONUT_MILK  = { "它有坚果的味道。", }
	-- Liquor (x5+)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.LIQUOR = { "爷爷称它为高球。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MARGARITA = { "一杯勇气。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PINA_COLADA = { "上面有一把小伞。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.DAIQUIRI = { "上面也有一把小伞。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.VINO = { "奶奶在烹饪时会用到这个。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PINT_NOIR = { "奶奶在烹饪时会用到这个。", }
	-- Meats (Beef) (x5)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEEF_BUTTER = { "请提交对检查报价的想法。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.KIYMALI_PIDE  = { "请提交对检查报价的想法。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.COLDCUTS = { "完全的胡言乱语。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BRACIOLE = { "卷起来的肉条。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEEF_STIRFRY = { "请提交对检查报价的想法。", } 
	-- Meats (Pork) (x5+)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SAUSAGE_GRAVY = { "油腻多汁的美味。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.DUMPLING_PORK  = { "请提交对检查报价的想法。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SPICED_SAUSAGE  = { "请提交对检查报价的想法。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SAUSAGE_COOKED  = { "请提交对检查报价的想法。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SAUSAGE_DRIED  = { "请提交对检查报价的想法。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SPICED_HAM  = { "请提交对检查报价的想法。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SWEET_N_SOUR = { "美味、酸甜、多汁的风味。", }
	-- Meats (Poultry) (x3)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEEFALO_WINGS = { "小小的辣鸡翅。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ROLLATINI = { "卷起来的刺人食物。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PICATTA = { "现在有点苦。", }
	-- Meats (Seafood) (x3)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SURF_N_TURF = { "这两样东西一起会好吃吗？", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.STUFFED_TOMANGO = { "我从没见过这样的东西。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.FISH_N_CHIPS = { "就像家乡的酒吧一样。", }
	-- Meats (Shellfish) (x3)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.LOBSTER_FAKED = { "有这么多腿，它为什么不从锅里爬出来？", }
	-- Mushrooms (4+)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CITRUS_MUSHROOM = { "酸味、土味、黏黏的口感。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MUSHROOM_BURGER = { "加了肉之后更健康。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MUSHROOM_MALODY = { "不太好吃的蘑菇混合物。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MUSHROOM_MEDLEY = { "愉悦的蘑菇混合物。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MUSHROOM_STEW = { "味道比气味好闻多了。", }
	-- Salads (4)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SALAD_CARROT = { "有益于我们的眼睛。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SALAD_GRAPE = { "带有水果味的沙拉。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SALAD_WALDORF = { "带有肉块的沙拉。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SALAD_YAMION = { "气味很浓的沙拉。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SALAD_BLOOM = { "一份色彩缤纷的沙拉。", }
	-- Soups (x5)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GAZPACHO = { "我也不会这样吃它们。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CACTUS_SOUP = { "妈妈在我生病时会煮汤。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SOUP_CHOWDER = { "鱼肉在浓郁的奶油中煮熟。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GUMBO = { "辣辣的汤。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SOUP_SQUASH = { "液体南瓜。", }
	-- Snacks (x7 +)
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ALOO_TIKI = { "像脆脆的小虫子一样。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CHEESE_LOG = { "可食用的木棍。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.NUT_BUTTER = { "脂肪丰富的坚果奶油。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PORRIDGE = { "就像妈妈做的一样。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GRUEL = { "几乎和爸爸做的一样。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.YAMION_RINGS = { "土豆变成了圆环。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.POPCORN_BUTTERY = { "没有爆米花，星期二我们该干什么呢。", } -- Anthony T. Hicks
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TWICE_BAKED = { "它的香味让我们垂涎欲滴。", }


STRINGS.CHARACTERS.WEBBER.DESCRIBE.CASSEROLE = { "好吃到我们做了两次。", }
	-- Crops & Seeds
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GRAPRICOT = { "一串核果。", } -- Drupe: Botanical term for a fruit with a single pit or seed
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GRAPRICOT_COOKED = { "多汁，就像饱胀的蜱虫。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GRAPRICOT_SEEDS = { "我们可以用这些种子种植一些东西。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.LIMON = { "这个不好吃。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.LIMON_COOKED = { "如果加糖，可能会变得好吃起来。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.LIMON_SEEDS = { "我们可以用这些种子种植一些东西。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TOMANGO = { "妈妈会从爷爷的花园里摘这些。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TOMANGO_COOKED = { "妈妈做的时候我不会吃这些。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TOMANGO_SEEDS = { "我们可以用这些种子种植一些东西。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.YAMION = { "爷爷称它们为地苹果。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.YAMION_COOKED = { "它的气味让我们流泪。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.YAMION_SEEDS = { "我们可以用这些种子种植一些东西。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GARLEEK = { "我靠近它眼睛就会流泪。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GARLEEK_COOKED = { "它闻起来像是奶奶的厨房。", }
	-- Shipwrecked Crops
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PAPAYANAPPLE = { "更多的树上食物。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PAPAYANAPPLE_COOKED = { "这个也需要一把小伞。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ZUCCHILLI = { "啊！它会灼伤！", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ZUCCHILLI_COOKED = { "像火焰的小片。", }
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ZUCCHILLI_SEEDS = { "我们可以用这些种子种植一些辣东西。", }
-- Grandpa used to have these at the pub.



-- =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+    DESCRIPTIONS.WINONA     =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+



-- =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+    DESCRIPTIONS.WORTOX     =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+



-- =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+    DESCRIPTIONS.WORMWOOD     =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+



-- =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+    DESCRIPTIONS.WARLEY     =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+


-- STRINGS.CHARACTERS.WARLEY.DESCRIBE.DRAGON_ROLL  = { "A crunchy texture of tempura inside a sushi roll.", }
-- STRINGS.CHARACTERS.WARLEY.DESCRIBE.FLOUR_GROUND = { "Now I can make pollenaise.", } -- Description is better for Warley
-- STRINGS.CHARACTERS.WARLEY.DESCRIBE.SLURRY_SEAFOOD  = { "A slimy salmagundi.", }

-- STRINGS.CHARACTERS.WOODLEGS.DESCRIBE.SLURRY_SEAFOOD  = { "Reminds me of my old chum.", } -- Chum, chopped fish thrown as bait 